export default {
  // Can be used to set padding around the entire component (eg paddingInline: 'space020')
  pagination: {
    small: {},
    medium: {},
    large: {},
  },
  paginationItem: {
    small: {
      typographyPreset: 'utilityButton010',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      minHeight: 'sizing050',
      minWidth: 'sizing050',
    },
    medium: {
      typographyPreset: 'utilityButton020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      minHeight: 'sizing060',
      minWidth: 'sizing060',
    },
    large: {
      typographyPreset: 'utilityButton030',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      minHeight: 'sizing070',
      minWidth: 'sizing070',
    },
  },
  paginationItemFirst: {
    small: {
      iconSize: 'iconSize010',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing050',
    },
    medium: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing060',
    },
    large: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing070',
    },
  },
  paginationItemPrev: {
    small: {
      iconSize: 'iconSize010',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing050',
    },
    medium: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing060',
    },
    large: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing070',
    },
  },
  paginationItemNext: {
    small: {
      iconSize: 'iconSize010',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing050',
    },
    medium: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing060',
    },
    large: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      marginInline: 'space000',
      width: 'sizing070',
    },
  },
  paginationItemLast: {
    small: {
      iconSize: 'iconSize010',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing050',
    },
    medium: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing060',
    },
    large: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItem',
      paddingInline: 'space020',
      paddingBlock: 'space000',
      marginInline: 'space010',
      width: 'sizing070',
    },
  },
  paginationItemTruncation: {
    small: {
      iconSize: 'iconSize010',
      stylePreset: 'paginationItemNonInteractive',
      marginInline: 'space000',
      width: 'sizing050',
    },
    medium: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItemNonInteractive',
      marginInline: 'space000',
      width: 'sizing060',
    },
    large: {
      iconSize: 'iconSize020',
      stylePreset: 'paginationItemNonInteractive',
      marginInline: 'space000',
      width: 'sizing070',
    },
  },
  paginationItemNonInteractive: {
    small: {
      typographyPreset: 'utilityBody010',
      stylePreset: 'paginationItemNonInteractive',
      iconSize: 'iconSize010',
      paddingInline: 'space000',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
    medium: {
      typographyPreset: 'utilityBody020',
      stylePreset: 'paginationItemNonInteractive',
      iconSize: 'iconSize020',
      paddingInline: 'space000',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
    large: {
      typographyPreset: 'utilityBody030',
      stylePreset: 'paginationItemNonInteractive',
      iconSize: 'iconSize020',
      paddingInline: 'space000',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
  },
  paginationItemInteractive: {
    small: {
      typographyPreset: 'utilityButton010',
      stylePreset: 'paginationItemInteractive',
      iconSize: 'iconSize010',
      paddingInline: 'space020',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
    medium: {
      typographyPreset: 'utilityButton020',
      stylePreset: 'paginationItemInteractive',
      iconSize: 'iconSize020',
      paddingInline: 'space020',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
    large: {
      typographyPreset: 'utilityButton030',
      stylePreset: 'paginationItemInteractive',
      iconSize: 'iconSize020',
      paddingInline: 'space020',
      marginInline: 'space010',
      marginBlockEnd: 'space000',
    },
  },
};
