/* refer https://github.com/ampproject/amphtml/tree/master/extensions */
export const scriptVersions = {
  'amp-access': '0.1',
  'amp-accordion': '0.1',
  'amp-ad': '0.1',
  'amp-analytics': '0.1',
  'amp-anim': '0.1',
  'amp-audio': '0.1',
  'amp-brid-player': '0.1',
  'amp-brightcove': '0.1',
  'amp-carousel': '0.1',
  'amp-consent': '0.1',
  'amp-dailymotion': '0.1',
  'amp-dynamic-css-classes': '0.1',
  'amp-embed': '0.1',
  'amp-experiment': '0.1',
  'amp-facebook-comments': '0.1',
  'amp-facebook': '0.1',
  'amp-fit-text': '0.1',
  'amp-font': '0.1',
  'amp-form': '0.1',
  'amp-fx-flying-carpet': '0.1',
  'amp-gfycat': '0.1',
  'amp-iframe': '0.1',
  'amp-image-lightbox': '0.1',
  'amp-img': false, // built-in
  'amp-instagram': '0.1',
  'amp-install-serviceworker': '0.1',
  'amp-izlesene': '0.1',
  'amp-jwplayer': '0.1',
  'amp-kaltura-player': '0.1',
  'amp-lightbox': '0.1',
  'amp-list': '0.1',
  'amp-live-list': '0.1',
  'amp-mustache': '0.1',
  'amp-o2-player': '0.1',
  'amp-pinterest': '0.1',
  'amp-pixel': false, // built-in
  'amp-playbuzz': '0.1',
  'amp-reach-player': '0.1',
  'amp-reddit': '0.1',
  'amp-sidebar': '0.1',
  'amp-social-share': '0.1',
  'amp-soundcloud': '0.1',
  'amp-springboard-player': '0.1',
  'amp-sticky-ad': '1.0',
  'amp-twitter': '0.1',
  'amp-user-notification': '0.1',
  'amp-video': '0.1',
  'amp-vimeo': '0.1',
  'amp-vine': '0.1',
  'amp-youtube': '0.1',
};
export type ScriptsKey = keyof typeof scriptVersions;
