import * as React from 'react';

export * from './bookmark';
export * from './circle';
export * from './comment';
export * from './copy-link';
export * from './email';
export * from './facebook';
export * from './github';
export * from './menu';
export * from './placeholder';
export * from './save-active';
export * from './save-inactive';
export * from './svg';
export * from './pause';
export * from './play';
export * from './twitter';
export * from './volume-down';
export * from './volume-mute';
export * from './volume-up';
export * from './whatsapp';
export * from './forward10';
export * from './replay10';
export type IconComponent = React.ComponentType;
