/* eslint-disable no-param-reassign */
import {bundleMDX} from 'mdx-bundler';
import path from 'path';

export default async function getMDXCode(source: string, pathToSource: string) {
  return bundleMDX({
    source,
    cwd: path.dirname(pathToSource),
    globals: {
      newskit: {
        varName: 'newskit',
        namedExports: ['InlineMessage'],
        defaultExport: false,
      },
    },
    esbuildOptions: options => {
      options.loader = {
        ...options.loader,
        '.png': 'file',
        '.jpg': 'file',
        '.mp4': 'file',
        '.svg': 'file',
        '.js': 'jsx',
      };

      options.minify = false;

      // we need to store files generated by file loader somewhere
      options.publicPath = '/static';
      options.write = true;
      options.outdir = path.join(process.cwd(), '/public/static');

      return options;
    },
  });
}
