// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StayPrimaryLandscape} from '@emotion-icons/material/StayPrimaryLandscape';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
StayPrimaryLandscape.displayName = 'IconOutlinedStayPrimaryLandscape';

export const IconOutlinedStayPrimaryLandscape = toNewsKitIcon(
  StayPrimaryLandscape,
);
