// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {OfflineBolt} from '@emotion-icons/material/OfflineBolt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
OfflineBolt['displayName'] = "IconOutlinedOfflineBolt";

export const IconOutlinedOfflineBolt = toNewsKitIcon(OfflineBolt);
