// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExploreOff} from '@emotion-icons/material/ExploreOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ExploreOff['displayName'] = "IconOutlinedExploreOff";

export const IconOutlinedExploreOff = toNewsKitIcon(ExploreOff);
