// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RemoveCircle} from '@emotion-icons/material/RemoveCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RemoveCircle['displayName'] = "IconOutlinedRemoveCircle";

export const IconOutlinedRemoveCircle = toNewsKitIcon(RemoveCircle);
