// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HistoryToggleOff} from '@emotion-icons/material/HistoryToggleOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HistoryToggleOff.displayName = 'IconOutlinedHistoryToggleOff';

export const IconOutlinedHistoryToggleOff = toNewsKitIcon(HistoryToggleOff);
