// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StackedLineChart} from '@emotion-icons/material/StackedLineChart';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
StackedLineChart['displayName'] = "IconOutlinedStackedLineChart";

export const IconOutlinedStackedLineChart = toNewsKitIcon(StackedLineChart);
