// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PersonOutline} from '@emotion-icons/material/PersonOutline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PersonOutline.displayName = 'IconOutlinedPersonOutline';

export const IconOutlinedPersonOutline = toNewsKitIcon(PersonOutline);
