// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Brightness3} from '@emotion-icons/material/Brightness3';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Brightness3.displayName = 'IconOutlinedBrightness3';

export const IconOutlinedBrightness3 = toNewsKitIcon(Brightness3);
