// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WbCloudy} from '@emotion-icons/material/WbCloudy';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
WbCloudy.displayName = 'IconOutlinedWbCloudy';

export const IconOutlinedWbCloudy = toNewsKitIcon(WbCloudy);
