// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AirlineSeatLegroomNormal} from '@emotion-icons/material/AirlineSeatLegroomNormal';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AirlineSeatLegroomNormal['displayName'] = "IconOutlinedAirlineSeatLegroomNormal";

export const IconOutlinedAirlineSeatLegroomNormal = toNewsKitIcon(AirlineSeatLegroomNormal);
