// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HdrOn} from '@emotion-icons/material/HdrOn';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HdrOn['displayName'] = "IconOutlinedHdrOn";

export const IconOutlinedHdrOn = toNewsKitIcon(HdrOn);
