// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VideocamOff} from '@emotion-icons/material/VideocamOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
VideocamOff.displayName = 'IconOutlinedVideocamOff';

export const IconOutlinedVideocamOff = toNewsKitIcon(VideocamOff);
