// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ControlPoint} from '@emotion-icons/material/ControlPoint';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ControlPoint.displayName = 'IconOutlinedControlPoint';

export const IconOutlinedControlPoint = toNewsKitIcon(ControlPoint);
