// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsBackupRestore} from '@emotion-icons/material/SettingsBackupRestore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsBackupRestore.displayName = 'IconOutlinedSettingsBackupRestore';

export const IconOutlinedSettingsBackupRestore = toNewsKitIcon(
  SettingsBackupRestore,
);
