// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NoMeetingRoom} from '@emotion-icons/material/NoMeetingRoom';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NoMeetingRoom.displayName = 'IconOutlinedNoMeetingRoom';

export const IconOutlinedNoMeetingRoom = toNewsKitIcon(NoMeetingRoom);
