// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RecentActors} from '@emotion-icons/material/RecentActors';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RecentActors['displayName'] = "IconOutlinedRecentActors";

export const IconOutlinedRecentActors = toNewsKitIcon(RecentActors);
