// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FireExtinguisher} from '@emotion-icons/material/FireExtinguisher';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FireExtinguisher.displayName = 'IconOutlinedFireExtinguisher';

export const IconOutlinedFireExtinguisher = toNewsKitIcon(FireExtinguisher);
