// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ReportOff} from '@emotion-icons/material/ReportOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ReportOff['displayName'] = "IconOutlinedReportOff";

export const IconOutlinedReportOff = toNewsKitIcon(ReportOff);
