// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EmojiSymbols} from '@emotion-icons/material/EmojiSymbols';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
EmojiSymbols.displayName = 'IconOutlinedEmojiSymbols';

export const IconOutlinedEmojiSymbols = toNewsKitIcon(EmojiSymbols);
