// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FitnessCenter} from '@emotion-icons/material/FitnessCenter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FitnessCenter['displayName'] = "IconOutlinedFitnessCenter";

export const IconOutlinedFitnessCenter = toNewsKitIcon(FitnessCenter);
