// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Refresh} from '@emotion-icons/material/Refresh';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Refresh.displayName = 'IconOutlinedRefresh';

export const IconOutlinedRefresh = toNewsKitIcon(Refresh);
