// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ViewWeek} from '@emotion-icons/material/ViewWeek';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ViewWeek['displayName'] = "IconOutlinedViewWeek";

export const IconOutlinedViewWeek = toNewsKitIcon(ViewWeek);
