// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {KeyboardArrowLeft} from '@emotion-icons/material/KeyboardArrowLeft';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
KeyboardArrowLeft['displayName'] = "IconOutlinedKeyboardArrowLeft";

export const IconOutlinedKeyboardArrowLeft = toNewsKitIcon(KeyboardArrowLeft);
