// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CameraFront} from '@emotion-icons/material/CameraFront';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CameraFront.displayName = 'IconOutlinedCameraFront';

export const IconOutlinedCameraFront = toNewsKitIcon(CameraFront);
