// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AirlineSeatReclineExtra} from '@emotion-icons/material/AirlineSeatReclineExtra';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AirlineSeatReclineExtra.displayName = 'IconOutlinedAirlineSeatReclineExtra';

export const IconOutlinedAirlineSeatReclineExtra = toNewsKitIcon(
  AirlineSeatReclineExtra,
);
