// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {UnfoldLess} from '@emotion-icons/material/UnfoldLess';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
UnfoldLess['displayName'] = "IconOutlinedUnfoldLess";

export const IconOutlinedUnfoldLess = toNewsKitIcon(UnfoldLess);
