// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ZoomOut} from '@emotion-icons/material/ZoomOut';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ZoomOut['displayName'] = "IconOutlinedZoomOut";

export const IconOutlinedZoomOut = toNewsKitIcon(ZoomOut);
