// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CameraRear} from '@emotion-icons/material/CameraRear';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CameraRear['displayName'] = "IconOutlinedCameraRear";

export const IconOutlinedCameraRear = toNewsKitIcon(CameraRear);
