// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DesktopAccessDisabled} from '@emotion-icons/material/DesktopAccessDisabled';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DesktopAccessDisabled['displayName'] = "IconOutlinedDesktopAccessDisabled";

export const IconOutlinedDesktopAccessDisabled = toNewsKitIcon(DesktopAccessDisabled);
