// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PeopleOutline} from '@emotion-icons/material/PeopleOutline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PeopleOutline['displayName'] = "IconOutlinedPeopleOutline";

export const IconOutlinedPeopleOutline = toNewsKitIcon(PeopleOutline);
