// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Vibration} from '@emotion-icons/material/Vibration';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Vibration['displayName'] = "IconOutlinedVibration";

export const IconOutlinedVibration = toNewsKitIcon(Vibration);
