// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FilterHdr} from '@emotion-icons/material/FilterHdr';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FilterHdr['displayName'] = "IconOutlinedFilterHdr";

export const IconOutlinedFilterHdr = toNewsKitIcon(FilterHdr);
