// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {KeyboardCapslock} from '@emotion-icons/material/KeyboardCapslock';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
KeyboardCapslock.displayName = 'IconOutlinedKeyboardCapslock';

export const IconOutlinedKeyboardCapslock = toNewsKitIcon(KeyboardCapslock);
