// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Visibility} from '@emotion-icons/material/Visibility';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Visibility['displayName'] = "IconOutlinedVisibility";

export const IconOutlinedVisibility = toNewsKitIcon(Visibility);
