// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Flight} from '@emotion-icons/material/Flight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Flight['displayName'] = "IconOutlinedFlight";

export const IconOutlinedFlight = toNewsKitIcon(Flight);
