// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ViewCarousel} from '@emotion-icons/material/ViewCarousel';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ViewCarousel.displayName = 'IconOutlinedViewCarousel';

export const IconOutlinedViewCarousel = toNewsKitIcon(ViewCarousel);
