// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {GetApp} from '@emotion-icons/material/GetApp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
GetApp.displayName = 'IconOutlinedGetApp';

export const IconOutlinedGetApp = toNewsKitIcon(GetApp);
