// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Apartment} from '@emotion-icons/material/Apartment';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Apartment.displayName = 'IconOutlinedApartment';

export const IconOutlinedApartment = toNewsKitIcon(Apartment);
