// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Clear} from '@emotion-icons/material/Clear';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Clear.displayName = 'IconOutlinedClear';

export const IconOutlinedClear = toNewsKitIcon(Clear);
