// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocationCity} from '@emotion-icons/material/LocationCity';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocationCity['displayName'] = "IconOutlinedLocationCity";

export const IconOutlinedLocationCity = toNewsKitIcon(LocationCity);
