// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WheelchairPickup} from '@emotion-icons/material/WheelchairPickup';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
WheelchairPickup.displayName = 'IconOutlinedWheelchairPickup';

export const IconOutlinedWheelchairPickup = toNewsKitIcon(WheelchairPickup);
