// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Rotate90DegreesCcw} from '@emotion-icons/material/Rotate90DegreesCcw';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Rotate90DegreesCcw.displayName = 'IconOutlinedRotate90DegreesCcw';

export const IconOutlinedRotate90DegreesCcw = toNewsKitIcon(Rotate90DegreesCcw);
