// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MoneyOff} from '@emotion-icons/material/MoneyOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MoneyOff.displayName = 'IconOutlinedMoneyOff';

export const IconOutlinedMoneyOff = toNewsKitIcon(MoneyOff);
