// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Snooze} from '@emotion-icons/material/Snooze';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Snooze['displayName'] = "IconOutlinedSnooze";

export const IconOutlinedSnooze = toNewsKitIcon(Snooze);
