// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FiberManualRecord} from '@emotion-icons/material/FiberManualRecord';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FiberManualRecord['displayName'] = "IconOutlinedFiberManualRecord";

export const IconOutlinedFiberManualRecord = toNewsKitIcon(FiberManualRecord);
