// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Loop} from '@emotion-icons/material/Loop';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Loop['displayName'] = "IconOutlinedLoop";

export const IconOutlinedLoop = toNewsKitIcon(Loop);
