// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FontDownload} from '@emotion-icons/material/FontDownload';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FontDownload['displayName'] = "IconOutlinedFontDownload";

export const IconOutlinedFontDownload = toNewsKitIcon(FontDownload);
