// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BrokenImage} from '@emotion-icons/material/BrokenImage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BrokenImage.displayName = 'IconOutlinedBrokenImage';

export const IconOutlinedBrokenImage = toNewsKitIcon(BrokenImage);
