// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddAlert} from '@emotion-icons/material/AddAlert';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AddAlert.displayName = 'IconOutlinedAddAlert';

export const IconOutlinedAddAlert = toNewsKitIcon(AddAlert);
