// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ElectricCar} from '@emotion-icons/material/ElectricCar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ElectricCar['displayName'] = "IconOutlinedElectricCar";

export const IconOutlinedElectricCar = toNewsKitIcon(ElectricCar);
