// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PregnantWoman} from '@emotion-icons/material/PregnantWoman';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PregnantWoman.displayName = 'IconOutlinedPregnantWoman';

export const IconOutlinedPregnantWoman = toNewsKitIcon(PregnantWoman);
