// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SubdirectoryArrowLeft} from '@emotion-icons/material/SubdirectoryArrowLeft';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SubdirectoryArrowLeft['displayName'] = "IconOutlinedSubdirectoryArrowLeft";

export const IconOutlinedSubdirectoryArrowLeft = toNewsKitIcon(SubdirectoryArrowLeft);
