// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalSee} from '@emotion-icons/material/LocalSee';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalSee['displayName'] = "IconOutlinedLocalSee";

export const IconOutlinedLocalSee = toNewsKitIcon(LocalSee);
