// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsPower} from '@emotion-icons/material/SettingsPower';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsPower.displayName = 'IconOutlinedSettingsPower';

export const IconOutlinedSettingsPower = toNewsKitIcon(SettingsPower);
