// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {InvertColors} from '@emotion-icons/material/InvertColors';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
InvertColors['displayName'] = "IconOutlinedInvertColors";

export const IconOutlinedInvertColors = toNewsKitIcon(InvertColors);
