// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DeveloperBoard} from '@emotion-icons/material/DeveloperBoard';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DeveloperBoard.displayName = 'IconOutlinedDeveloperBoard';

export const IconOutlinedDeveloperBoard = toNewsKitIcon(DeveloperBoard);
