// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhoneBluetoothSpeaker} from '@emotion-icons/material/PhoneBluetoothSpeaker';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PhoneBluetoothSpeaker.displayName = 'IconOutlinedPhoneBluetoothSpeaker';

export const IconOutlinedPhoneBluetoothSpeaker = toNewsKitIcon(
  PhoneBluetoothSpeaker,
);
