// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LeakAdd} from '@emotion-icons/material/LeakAdd';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LeakAdd.displayName = 'IconOutlinedLeakAdd';

export const IconOutlinedLeakAdd = toNewsKitIcon(LeakAdd);
