// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Storefront} from '@emotion-icons/material/Storefront';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Storefront['displayName'] = "IconOutlinedStorefront";

export const IconOutlinedStorefront = toNewsKitIcon(Storefront);
