// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Redo} from '@emotion-icons/material/Redo';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Redo.displayName = 'IconOutlinedRedo';

export const IconOutlinedRedo = toNewsKitIcon(Redo);
