// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SyncAlt} from '@emotion-icons/material/SyncAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SyncAlt.displayName = 'IconOutlinedSyncAlt';

export const IconOutlinedSyncAlt = toNewsKitIcon(SyncAlt);
