// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Mms} from '@emotion-icons/material/Mms';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Mms.displayName = 'IconOutlinedMms';

export const IconOutlinedMms = toNewsKitIcon(Mms);
