// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CloudQueue} from '@emotion-icons/material/CloudQueue';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CloudQueue['displayName'] = "IconOutlinedCloudQueue";

export const IconOutlinedCloudQueue = toNewsKitIcon(CloudQueue);
