// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Book} from '@emotion-icons/material/Book';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Book.displayName = 'IconOutlinedBook';

export const IconOutlinedBook = toNewsKitIcon(Book);
