// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Museum} from '@emotion-icons/material/Museum';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Museum.displayName = 'IconOutlinedMuseum';

export const IconOutlinedMuseum = toNewsKitIcon(Museum);
