// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Panorama} from '@emotion-icons/material/Panorama';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Panorama['displayName'] = "IconOutlinedPanorama";

export const IconOutlinedPanorama = toNewsKitIcon(Panorama);
