// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhoneAndroid} from '@emotion-icons/material/PhoneAndroid';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PhoneAndroid.displayName = 'IconOutlinedPhoneAndroid';

export const IconOutlinedPhoneAndroid = toNewsKitIcon(PhoneAndroid);
