// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VolumeDown} from '@emotion-icons/material/VolumeDown';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
VolumeDown.displayName = 'IconOutlinedVolumeDown';

export const IconOutlinedVolumeDown = toNewsKitIcon(VolumeDown);
