// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Audiotrack} from '@emotion-icons/material/Audiotrack';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Audiotrack.displayName = 'IconOutlinedAudiotrack';

export const IconOutlinedAudiotrack = toNewsKitIcon(Audiotrack);
