// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HelpCenter} from '@emotion-icons/material/HelpCenter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HelpCenter['displayName'] = "IconOutlinedHelpCenter";

export const IconOutlinedHelpCenter = toNewsKitIcon(HelpCenter);
