// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Brightness6} from '@emotion-icons/material/Brightness6';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Brightness6['displayName'] = "IconOutlinedBrightness6";

export const IconOutlinedBrightness6 = toNewsKitIcon(Brightness6);
