// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {OutlinedFlag} from '@emotion-icons/material/OutlinedFlag';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
OutlinedFlag['displayName'] = "IconOutlinedOutlinedFlag";

export const IconOutlinedOutlinedFlag = toNewsKitIcon(OutlinedFlag);
