// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DragHandle} from '@emotion-icons/material/DragHandle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DragHandle['displayName'] = "IconOutlinedDragHandle";

export const IconOutlinedDragHandle = toNewsKitIcon(DragHandle);
