// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RoundedCorner} from '@emotion-icons/material/RoundedCorner';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RoundedCorner.displayName = 'IconOutlinedRoundedCorner';

export const IconOutlinedRoundedCorner = toNewsKitIcon(RoundedCorner);
