// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SmartButton} from '@emotion-icons/material/SmartButton';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SmartButton.displayName = 'IconOutlinedSmartButton';

export const IconOutlinedSmartButton = toNewsKitIcon(SmartButton);
