// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ShoppingCart} from '@emotion-icons/material/ShoppingCart';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ShoppingCart.displayName = 'IconOutlinedShoppingCart';

export const IconOutlinedShoppingCart = toNewsKitIcon(ShoppingCart);
