// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsBluetooth} from '@emotion-icons/material/SettingsBluetooth';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsBluetooth['displayName'] = "IconOutlinedSettingsBluetooth";

export const IconOutlinedSettingsBluetooth = toNewsKitIcon(SettingsBluetooth);
