// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EmojiEvents} from '@emotion-icons/material/EmojiEvents';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
EmojiEvents['displayName'] = "IconOutlinedEmojiEvents";

export const IconOutlinedEmojiEvents = toNewsKitIcon(EmojiEvents);
