// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TextRotationAngledown} from '@emotion-icons/material/TextRotationAngledown';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TextRotationAngledown.displayName = 'IconOutlinedTextRotationAngledown';

export const IconOutlinedTextRotationAngledown = toNewsKitIcon(
  TextRotationAngledown,
);
