// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AccessTime} from '@emotion-icons/material/AccessTime';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AccessTime['displayName'] = "IconOutlinedAccessTime";

export const IconOutlinedAccessTime = toNewsKitIcon(AccessTime);
