// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhonelinkOff} from '@emotion-icons/material/PhonelinkOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PhonelinkOff.displayName = 'IconOutlinedPhonelinkOff';

export const IconOutlinedPhonelinkOff = toNewsKitIcon(PhonelinkOff);
