// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Wifi} from '@emotion-icons/material/Wifi';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Wifi.displayName = 'IconOutlinedWifi';

export const IconOutlinedWifi = toNewsKitIcon(Wifi);
