// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsBoat} from '@emotion-icons/material/DirectionsBoat';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DirectionsBoat.displayName = 'IconOutlinedDirectionsBoat';

export const IconOutlinedDirectionsBoat = toNewsKitIcon(DirectionsBoat);
