// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PausePresentation} from '@emotion-icons/material/PausePresentation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PausePresentation.displayName = 'IconOutlinedPausePresentation';

export const IconOutlinedPausePresentation = toNewsKitIcon(PausePresentation);
