// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddCircle} from '@emotion-icons/material/AddCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AddCircle['displayName'] = "IconOutlinedAddCircle";

export const IconOutlinedAddCircle = toNewsKitIcon(AddCircle);
