// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Architecture} from '@emotion-icons/material/Architecture';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Architecture['displayName'] = "IconOutlinedArchitecture";

export const IconOutlinedArchitecture = toNewsKitIcon(Architecture);
