// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ToggleOn} from '@emotion-icons/material/ToggleOn';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ToggleOn.displayName = 'IconOutlinedToggleOn';

export const IconOutlinedToggleOn = toNewsKitIcon(ToggleOn);
