// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Hotel} from '@emotion-icons/material/Hotel';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Hotel['displayName'] = "IconOutlinedHotel";

export const IconOutlinedHotel = toNewsKitIcon(Hotel);
