// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Rule} from '@emotion-icons/material/Rule';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Rule.displayName = 'IconOutlinedRule';

export const IconOutlinedRule = toNewsKitIcon(Rule);
