// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {QueuePlayNext} from '@emotion-icons/material/QueuePlayNext';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
QueuePlayNext['displayName'] = "IconOutlinedQueuePlayNext";

export const IconOutlinedQueuePlayNext = toNewsKitIcon(QueuePlayNext);
