// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BookOnline} from '@emotion-icons/material/BookOnline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BookOnline.displayName = 'IconOutlinedBookOnline';

export const IconOutlinedBookOnline = toNewsKitIcon(BookOnline);
