// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Addchart} from '@emotion-icons/material/Addchart';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Addchart.displayName = 'IconOutlinedAddchart';

export const IconOutlinedAddchart = toNewsKitIcon(Addchart);
