// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AirportShuttle} from '@emotion-icons/material/AirportShuttle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AirportShuttle['displayName'] = "IconOutlinedAirportShuttle";

export const IconOutlinedAirportShuttle = toNewsKitIcon(AirportShuttle);
