// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Crop} from '@emotion-icons/material/Crop';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Crop.displayName = 'IconOutlinedCrop';

export const IconOutlinedCrop = toNewsKitIcon(Crop);
