// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SignalCellularAlt} from '@emotion-icons/material/SignalCellularAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SignalCellularAlt['displayName'] = "IconOutlinedSignalCellularAlt";

export const IconOutlinedSignalCellularAlt = toNewsKitIcon(SignalCellularAlt);
