// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MilitaryTech} from '@emotion-icons/material/MilitaryTech';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MilitaryTech['displayName'] = "IconOutlinedMilitaryTech";

export const IconOutlinedMilitaryTech = toNewsKitIcon(MilitaryTech);
