// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RequestPage} from '@emotion-icons/material/RequestPage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RequestPage['displayName'] = "IconOutlinedRequestPage";

export const IconOutlinedRequestPage = toNewsKitIcon(RequestPage);
