// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalPolice} from '@emotion-icons/material/LocalPolice';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalPolice['displayName'] = "IconOutlinedLocalPolice";

export const IconOutlinedLocalPolice = toNewsKitIcon(LocalPolice);
