// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowRightAlt} from '@emotion-icons/material/ArrowRightAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ArrowRightAlt.displayName = 'IconOutlinedArrowRightAlt';

export const IconOutlinedArrowRightAlt = toNewsKitIcon(ArrowRightAlt);
