// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CardTravel} from '@emotion-icons/material/CardTravel';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CardTravel.displayName = 'IconOutlinedCardTravel';

export const IconOutlinedCardTravel = toNewsKitIcon(CardTravel);
