// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Traffic} from '@emotion-icons/material/Traffic';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Traffic['displayName'] = "IconOutlinedTraffic";

export const IconOutlinedTraffic = toNewsKitIcon(Traffic);
