// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MenuOpen} from '@emotion-icons/material/MenuOpen';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MenuOpen.displayName = 'IconOutlinedMenuOpen';

export const IconOutlinedMenuOpen = toNewsKitIcon(MenuOpen);
