// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ThumbDown} from '@emotion-icons/material/ThumbDown';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ThumbDown.displayName = 'IconOutlinedThumbDown';

export const IconOutlinedThumbDown = toNewsKitIcon(ThumbDown);
