// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Exposure} from '@emotion-icons/material/Exposure';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Exposure['displayName'] = "IconOutlinedExposure";

export const IconOutlinedExposure = toNewsKitIcon(Exposure);
