// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AspectRatio} from '@emotion-icons/material/AspectRatio';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AspectRatio.displayName = 'IconOutlinedAspectRatio';

export const IconOutlinedAspectRatio = toNewsKitIcon(AspectRatio);
