// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ChromeReaderMode} from '@emotion-icons/material/ChromeReaderMode';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ChromeReaderMode.displayName = 'IconOutlinedChromeReaderMode';

export const IconOutlinedChromeReaderMode = toNewsKitIcon(ChromeReaderMode);
