// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SubdirectoryArrowRight} from '@emotion-icons/material/SubdirectoryArrowRight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SubdirectoryArrowRight['displayName'] = "IconOutlinedSubdirectoryArrowRight";

export const IconOutlinedSubdirectoryArrowRight = toNewsKitIcon(SubdirectoryArrowRight);
