// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SdStorage} from '@emotion-icons/material/SdStorage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SdStorage['displayName'] = "IconOutlinedSdStorage";

export const IconOutlinedSdStorage = toNewsKitIcon(SdStorage);
