// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AccountTree} from '@emotion-icons/material/AccountTree';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AccountTree['displayName'] = "IconOutlinedAccountTree";

export const IconOutlinedAccountTree = toNewsKitIcon(AccountTree);
