// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocationOn} from '@emotion-icons/material/LocationOn';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocationOn.displayName = 'IconOutlinedLocationOn';

export const IconOutlinedLocationOn = toNewsKitIcon(LocationOn);
