// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FiberPin} from '@emotion-icons/material/FiberPin';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FiberPin.displayName = 'IconOutlinedFiberPin';

export const IconOutlinedFiberPin = toNewsKitIcon(FiberPin);
