// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsBike} from '@emotion-icons/material/DirectionsBike';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DirectionsBike.displayName = 'IconOutlinedDirectionsBike';

export const IconOutlinedDirectionsBike = toNewsKitIcon(DirectionsBike);
