// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsTennis} from '@emotion-icons/material/SportsTennis';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SportsTennis.displayName = 'IconOutlinedSportsTennis';

export const IconOutlinedSportsTennis = toNewsKitIcon(SportsTennis);
