// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalMall} from '@emotion-icons/material/LocalMall';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalMall.displayName = 'IconOutlinedLocalMall';

export const IconOutlinedLocalMall = toNewsKitIcon(LocalMall);
