// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DoNotTouch} from '@emotion-icons/material/DoNotTouch';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DoNotTouch['displayName'] = "IconOutlinedDoNotTouch";

export const IconOutlinedDoNotTouch = toNewsKitIcon(DoNotTouch);
