// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CropRotate} from '@emotion-icons/material/CropRotate';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CropRotate['displayName'] = "IconOutlinedCropRotate";

export const IconOutlinedCropRotate = toNewsKitIcon(CropRotate);
