// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Mood} from '@emotion-icons/material/Mood';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Mood.displayName = 'IconOutlinedMood';

export const IconOutlinedMood = toNewsKitIcon(Mood);
