// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LibraryAdd} from '@emotion-icons/material/LibraryAdd';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LibraryAdd.displayName = 'IconOutlinedLibraryAdd';

export const IconOutlinedLibraryAdd = toNewsKitIcon(LibraryAdd);
