// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Elderly} from '@emotion-icons/material/Elderly';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Elderly.displayName = 'IconOutlinedElderly';

export const IconOutlinedElderly = toNewsKitIcon(Elderly);
