// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Forward30} from '@emotion-icons/material/Forward30';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Forward30.displayName = 'IconOutlinedForward30';

export const IconOutlinedForward30 = toNewsKitIcon(Forward30);
