// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TripOrigin} from '@emotion-icons/material/TripOrigin';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TripOrigin['displayName'] = "IconOutlinedTripOrigin";

export const IconOutlinedTripOrigin = toNewsKitIcon(TripOrigin);
