// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsSubway} from '@emotion-icons/material/DirectionsSubway';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DirectionsSubway['displayName'] = "IconOutlinedDirectionsSubway";

export const IconOutlinedDirectionsSubway = toNewsKitIcon(DirectionsSubway);
