// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Class} from '@emotion-icons/material/Class';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Class['displayName'] = "IconOutlinedClass";

export const IconOutlinedClass = toNewsKitIcon(Class);
