// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ThumbDownAlt} from '@emotion-icons/material/ThumbDownAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ThumbDownAlt['displayName'] = "IconOutlinedThumbDownAlt";

export const IconOutlinedThumbDownAlt = toNewsKitIcon(ThumbDownAlt);
