// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CancelScheduleSend} from '@emotion-icons/material/CancelScheduleSend';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CancelScheduleSend['displayName'] = "IconOutlinedCancelScheduleSend";

export const IconOutlinedCancelScheduleSend = toNewsKitIcon(CancelScheduleSend);
