// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsOff} from '@emotion-icons/material/DirectionsOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DirectionsOff.displayName = 'IconOutlinedDirectionsOff';

export const IconOutlinedDirectionsOff = toNewsKitIcon(DirectionsOff);
