// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Drafts} from '@emotion-icons/material/Drafts';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Drafts['displayName'] = "IconOutlinedDrafts";

export const IconOutlinedDrafts = toNewsKitIcon(Drafts);
