// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BlurCircular} from '@emotion-icons/material/BlurCircular';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BlurCircular.displayName = 'IconOutlinedBlurCircular';

export const IconOutlinedBlurCircular = toNewsKitIcon(BlurCircular);
