// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CastForEducation} from '@emotion-icons/material/CastForEducation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CastForEducation.displayName = 'IconOutlinedCastForEducation';

export const IconOutlinedCastForEducation = toNewsKitIcon(CastForEducation);
