// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SetMeal} from '@emotion-icons/material/SetMeal';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SetMeal['displayName'] = "IconOutlinedSetMeal";

export const IconOutlinedSetMeal = toNewsKitIcon(SetMeal);
