// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LooksOne} from '@emotion-icons/material/LooksOne';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LooksOne.displayName = 'IconOutlinedLooksOne';

export const IconOutlinedLooksOne = toNewsKitIcon(LooksOne);
