// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FolderSpecial} from '@emotion-icons/material/FolderSpecial';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FolderSpecial.displayName = 'IconOutlinedFolderSpecial';

export const IconOutlinedFolderSpecial = toNewsKitIcon(FolderSpecial);
