// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ReduceCapacity} from '@emotion-icons/material/ReduceCapacity';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ReduceCapacity.displayName = 'IconOutlinedReduceCapacity';

export const IconOutlinedReduceCapacity = toNewsKitIcon(ReduceCapacity);
