// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PedalBike} from '@emotion-icons/material/PedalBike';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PedalBike.displayName = 'IconOutlinedPedalBike';

export const IconOutlinedPedalBike = toNewsKitIcon(PedalBike);
