// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MarkunreadMailbox} from '@emotion-icons/material/MarkunreadMailbox';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MarkunreadMailbox.displayName = 'IconOutlinedMarkunreadMailbox';

export const IconOutlinedMarkunreadMailbox = toNewsKitIcon(MarkunreadMailbox);
