// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FlashOff} from '@emotion-icons/material/FlashOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FlashOff.displayName = 'IconOutlinedFlashOff';

export const IconOutlinedFlashOff = toNewsKitIcon(FlashOff);
