// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MenuBook} from '@emotion-icons/material/MenuBook';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MenuBook['displayName'] = "IconOutlinedMenuBook";

export const IconOutlinedMenuBook = toNewsKitIcon(MenuBook);
