// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DataUsage} from '@emotion-icons/material/DataUsage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DataUsage['displayName'] = "IconOutlinedDataUsage";

export const IconOutlinedDataUsage = toNewsKitIcon(DataUsage);
