// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ShortText} from '@emotion-icons/material/ShortText';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ShortText.displayName = 'IconOutlinedShortText';

export const IconOutlinedShortText = toNewsKitIcon(ShortText);
