// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsMma} from '@emotion-icons/material/SportsMma';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SportsMma.displayName = 'IconOutlinedSportsMma';

export const IconOutlinedSportsMma = toNewsKitIcon(SportsMma);
