// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BorderAll} from '@emotion-icons/material/BorderAll';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BorderAll['displayName'] = "IconOutlinedBorderAll";

export const IconOutlinedBorderAll = toNewsKitIcon(BorderAll);
