// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Web} from '@emotion-icons/material/Web';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Web.displayName = 'IconOutlinedWeb';

export const IconOutlinedWeb = toNewsKitIcon(Web);
