// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Coronavirus} from '@emotion-icons/material/Coronavirus';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Coronavirus['displayName'] = "IconOutlinedCoronavirus";

export const IconOutlinedCoronavirus = toNewsKitIcon(Coronavirus);
