// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Whatshot} from '@emotion-icons/material/Whatshot';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Whatshot['displayName'] = "IconOutlinedWhatshot";

export const IconOutlinedWhatshot = toNewsKitIcon(Whatshot);
