// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Equalizer} from '@emotion-icons/material/Equalizer';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Equalizer.displayName = 'IconOutlinedEqualizer';

export const IconOutlinedEqualizer = toNewsKitIcon(Equalizer);
