// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Loupe} from '@emotion-icons/material/Loupe';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Loupe.displayName = 'IconOutlinedLoupe';

export const IconOutlinedLoupe = toNewsKitIcon(Loupe);
