// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NearMeDisabled} from '@emotion-icons/material/NearMeDisabled';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NearMeDisabled.displayName = 'IconOutlinedNearMeDisabled';

export const IconOutlinedNearMeDisabled = toNewsKitIcon(NearMeDisabled);
