// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BookmarkBorder} from '@emotion-icons/material/BookmarkBorder';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BookmarkBorder.displayName = 'IconOutlinedBookmarkBorder';

export const IconOutlinedBookmarkBorder = toNewsKitIcon(BookmarkBorder);
