// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NoSim} from '@emotion-icons/material/NoSim';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NoSim['displayName'] = "IconOutlinedNoSim";

export const IconOutlinedNoSim = toNewsKitIcon(NoSim);
