// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CropFree} from '@emotion-icons/material/CropFree';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CropFree['displayName'] = "IconOutlinedCropFree";

export const IconOutlinedCropFree = toNewsKitIcon(CropFree);
