// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalGasStation} from '@emotion-icons/material/LocalGasStation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalGasStation['displayName'] = "IconOutlinedLocalGasStation";

export const IconOutlinedLocalGasStation = toNewsKitIcon(LocalGasStation);
