// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExposureNeg2} from '@emotion-icons/material/ExposureNeg2';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ExposureNeg2.displayName = 'IconOutlinedExposureNeg2';

export const IconOutlinedExposureNeg2 = toNewsKitIcon(ExposureNeg2);
