// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TouchApp} from '@emotion-icons/material/TouchApp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TouchApp.displayName = 'IconOutlinedTouchApp';

export const IconOutlinedTouchApp = toNewsKitIcon(TouchApp);
