// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FlashAuto} from '@emotion-icons/material/FlashAuto';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FlashAuto['displayName'] = "IconOutlinedFlashAuto";

export const IconOutlinedFlashAuto = toNewsKitIcon(FlashAuto);
