// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FiberNew} from '@emotion-icons/material/FiberNew';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FiberNew.displayName = 'IconOutlinedFiberNew';

export const IconOutlinedFiberNew = toNewsKitIcon(FiberNew);
