// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddCircleOutline} from '@emotion-icons/material/AddCircleOutline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AddCircleOutline['displayName'] = "IconOutlinedAddCircleOutline";

export const IconOutlinedAddCircleOutline = toNewsKitIcon(AddCircleOutline);
