// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Gavel} from '@emotion-icons/material/Gavel';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Gavel.displayName = 'IconOutlinedGavel';

export const IconOutlinedGavel = toNewsKitIcon(Gavel);
