// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatListNumberedRtl} from '@emotion-icons/material/FormatListNumberedRtl';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatListNumberedRtl.displayName = 'IconOutlinedFormatListNumberedRtl';

export const IconOutlinedFormatListNumberedRtl = toNewsKitIcon(
  FormatListNumberedRtl,
);
