// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BorderBottom} from '@emotion-icons/material/BorderBottom';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BorderBottom.displayName = 'IconOutlinedBorderBottom';

export const IconOutlinedBorderBottom = toNewsKitIcon(BorderBottom);
