// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Stars} from '@emotion-icons/material/Stars';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Stars.displayName = 'IconOutlinedStars';

export const IconOutlinedStars = toNewsKitIcon(Stars);
