// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Payments} from '@emotion-icons/material/Payments';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Payments['displayName'] = "IconOutlinedPayments";

export const IconOutlinedPayments = toNewsKitIcon(Payments);
