// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Work} from '@emotion-icons/material/Work';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Work['displayName'] = "IconOutlinedWork";

export const IconOutlinedWork = toNewsKitIcon(Work);
