// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Moped} from '@emotion-icons/material/Moped';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Moped['displayName'] = "IconOutlinedMoped";

export const IconOutlinedMoped = toNewsKitIcon(Moped);
