// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CheckBox} from '@emotion-icons/material/CheckBox';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CheckBox.displayName = 'IconOutlinedCheckBox';

export const IconOutlinedCheckBox = toNewsKitIcon(CheckBox);
