// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PauseCircleFilled} from '@emotion-icons/material/PauseCircleFilled';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PauseCircleFilled['displayName'] = "IconOutlinedPauseCircleFilled";

export const IconOutlinedPauseCircleFilled = toNewsKitIcon(PauseCircleFilled);
