// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Theaters} from '@emotion-icons/material/Theaters';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Theaters['displayName'] = "IconOutlinedTheaters";

export const IconOutlinedTheaters = toNewsKitIcon(Theaters);
