// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Looks5} from '@emotion-icons/material/Looks5';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Looks5.displayName = 'IconOutlinedLooks5';

export const IconOutlinedLooks5 = toNewsKitIcon(Looks5);
