// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Unsubscribe} from '@emotion-icons/material/Unsubscribe';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Unsubscribe['displayName'] = "IconOutlinedUnsubscribe";

export const IconOutlinedUnsubscribe = toNewsKitIcon(Unsubscribe);
