// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FilterNone} from '@emotion-icons/material/FilterNone';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FilterNone['displayName'] = "IconOutlinedFilterNone";

export const IconOutlinedFilterNone = toNewsKitIcon(FilterNone);
