// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Contacts} from '@emotion-icons/material/Contacts';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Contacts.displayName = 'IconOutlinedContacts';

export const IconOutlinedContacts = toNewsKitIcon(Contacts);
