// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FilterDrama} from '@emotion-icons/material/FilterDrama';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FilterDrama.displayName = 'IconOutlinedFilterDrama';

export const IconOutlinedFilterDrama = toNewsKitIcon(FilterDrama);
