// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ContentPaste} from '@emotion-icons/material/ContentPaste';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ContentPaste.displayName = 'IconOutlinedContentPaste';

export const IconOutlinedContentPaste = toNewsKitIcon(ContentPaste);
