// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsInputSvideo} from '@emotion-icons/material/SettingsInputSvideo';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsInputSvideo['displayName'] = "IconOutlinedSettingsInputSvideo";

export const IconOutlinedSettingsInputSvideo = toNewsKitIcon(SettingsInputSvideo);
