// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FastRewind} from '@emotion-icons/material/FastRewind';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FastRewind.displayName = 'IconOutlinedFastRewind';

export const IconOutlinedFastRewind = toNewsKitIcon(FastRewind);
