// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CameraEnhance} from '@emotion-icons/material/CameraEnhance';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CameraEnhance.displayName = 'IconOutlinedCameraEnhance';

export const IconOutlinedCameraEnhance = toNewsKitIcon(CameraEnhance);
