// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {KeyboardArrowUp} from '@emotion-icons/material/KeyboardArrowUp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
KeyboardArrowUp.displayName = 'IconOutlinedKeyboardArrowUp';

export const IconOutlinedKeyboardArrowUp = toNewsKitIcon(KeyboardArrowUp);
