// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SignalCellular4Bar} from '@emotion-icons/material/SignalCellular4Bar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SignalCellular4Bar['displayName'] = "IconOutlinedSignalCellular4Bar";

export const IconOutlinedSignalCellular4Bar = toNewsKitIcon(SignalCellular4Bar);
