// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CardGiftcard} from '@emotion-icons/material/CardGiftcard';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CardGiftcard.displayName = 'IconOutlinedCardGiftcard';

export const IconOutlinedCardGiftcard = toNewsKitIcon(CardGiftcard);
