// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Markunread} from '@emotion-icons/material/Markunread';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Markunread.displayName = 'IconOutlinedMarkunread';

export const IconOutlinedMarkunread = toNewsKitIcon(Markunread);
