// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {QrCodeScanner} from '@emotion-icons/material/QrCodeScanner';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
QrCodeScanner['displayName'] = "IconOutlinedQrCodeScanner";

export const IconOutlinedQrCodeScanner = toNewsKitIcon(QrCodeScanner);
