// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VolumeOff} from '@emotion-icons/material/VolumeOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
VolumeOff.displayName = 'IconOutlinedVolumeOff';

export const IconOutlinedVolumeOff = toNewsKitIcon(VolumeOff);
