// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Style} from '@emotion-icons/material/Style';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Style['displayName'] = "IconOutlinedStyle";

export const IconOutlinedStyle = toNewsKitIcon(Style);
