// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Highlight} from '@emotion-icons/material/Highlight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Highlight.displayName = 'IconOutlinedHighlight';

export const IconOutlinedHighlight = toNewsKitIcon(Highlight);
