// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PlaylistAdd} from '@emotion-icons/material/PlaylistAdd';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PlaylistAdd['displayName'] = "IconOutlinedPlaylistAdd";

export const IconOutlinedPlaylistAdd = toNewsKitIcon(PlaylistAdd);
