// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowForwardIos} from '@emotion-icons/material/ArrowForwardIos';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ArrowForwardIos.displayName = 'IconOutlinedArrowForwardIos';

export const IconOutlinedArrowForwardIos = toNewsKitIcon(ArrowForwardIos);
