// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NoDrinks} from '@emotion-icons/material/NoDrinks';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NoDrinks['displayName'] = "IconOutlinedNoDrinks";

export const IconOutlinedNoDrinks = toNewsKitIcon(NoDrinks);
