// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ScreenShare} from '@emotion-icons/material/ScreenShare';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ScreenShare['displayName'] = "IconOutlinedScreenShare";

export const IconOutlinedScreenShare = toNewsKitIcon(ScreenShare);
