// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Backspace} from '@emotion-icons/material/Backspace';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Backspace['displayName'] = "IconOutlinedBackspace";

export const IconOutlinedBackspace = toNewsKitIcon(Backspace);
