// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ImageAspectRatio} from '@emotion-icons/material/ImageAspectRatio';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ImageAspectRatio['displayName'] = "IconOutlinedImageAspectRatio";

export const IconOutlinedImageAspectRatio = toNewsKitIcon(ImageAspectRatio);
