// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HotTub} from '@emotion-icons/material/HotTub';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HotTub.displayName = 'IconOutlinedHotTub';

export const IconOutlinedHotTub = toNewsKitIcon(HotTub);
