// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Directions} from '@emotion-icons/material/Directions';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Directions['displayName'] = "IconOutlinedDirections";

export const IconOutlinedDirections = toNewsKitIcon(Directions);
