// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PanoramaHorizontal} from '@emotion-icons/material/PanoramaHorizontal';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PanoramaHorizontal['displayName'] = "IconOutlinedPanoramaHorizontal";

export const IconOutlinedPanoramaHorizontal = toNewsKitIcon(PanoramaHorizontal);
