// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ClosedCaption} from '@emotion-icons/material/ClosedCaption';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ClosedCaption.displayName = 'IconOutlinedClosedCaption';

export const IconOutlinedClosedCaption = toNewsKitIcon(ClosedCaption);
