// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AllOut} from '@emotion-icons/material/AllOut';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AllOut.displayName = 'IconOutlinedAllOut';

export const IconOutlinedAllOut = toNewsKitIcon(AllOut);
