// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RotateLeft} from '@emotion-icons/material/RotateLeft';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RotateLeft['displayName'] = "IconOutlinedRotateLeft";

export const IconOutlinedRotateLeft = toNewsKitIcon(RotateLeft);
