// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Tv} from '@emotion-icons/material/Tv';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Tv['displayName'] = "IconOutlinedTv";

export const IconOutlinedTv = toNewsKitIcon(Tv);
