// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatListBulleted} from '@emotion-icons/material/FormatListBulleted';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatListBulleted.displayName = 'IconOutlinedFormatListBulleted';

export const IconOutlinedFormatListBulleted = toNewsKitIcon(FormatListBulleted);
