// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BikeScooter} from '@emotion-icons/material/BikeScooter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BikeScooter.displayName = 'IconOutlinedBikeScooter';

export const IconOutlinedBikeScooter = toNewsKitIcon(BikeScooter);
