// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Kitchen} from '@emotion-icons/material/Kitchen';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Kitchen.displayName = 'IconOutlinedKitchen';

export const IconOutlinedKitchen = toNewsKitIcon(Kitchen);
