// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Room} from '@emotion-icons/material/Room';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Room['displayName'] = "IconOutlinedRoom";

export const IconOutlinedRoom = toNewsKitIcon(Room);
