// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ReadMore} from '@emotion-icons/material/ReadMore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ReadMore['displayName'] = "IconOutlinedReadMore";

export const IconOutlinedReadMore = toNewsKitIcon(ReadMore);
