// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NotificationsActive} from '@emotion-icons/material/NotificationsActive';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NotificationsActive.displayName = 'IconOutlinedNotificationsActive';

export const IconOutlinedNotificationsActive = toNewsKitIcon(
  NotificationsActive,
);
