// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Textsms} from '@emotion-icons/material/Textsms';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Textsms.displayName = 'IconOutlinedTextsms';

export const IconOutlinedTextsms = toNewsKitIcon(Textsms);
