// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsVolleyball} from '@emotion-icons/material/SportsVolleyball';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SportsVolleyball['displayName'] = "IconOutlinedSportsVolleyball";

export const IconOutlinedSportsVolleyball = toNewsKitIcon(SportsVolleyball);
