// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Cake} from '@emotion-icons/material/Cake';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Cake['displayName'] = "IconOutlinedCake";

export const IconOutlinedCake = toNewsKitIcon(Cake);
