// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatSize} from '@emotion-icons/material/FormatSize';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatSize['displayName'] = "IconOutlinedFormatSize";

export const IconOutlinedFormatSize = toNewsKitIcon(FormatSize);
