// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AssignmentInd} from '@emotion-icons/material/AssignmentInd';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AssignmentInd.displayName = 'IconOutlinedAssignmentInd';

export const IconOutlinedAssignmentInd = toNewsKitIcon(AssignmentInd);
