// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Pool} from '@emotion-icons/material/Pool';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Pool['displayName'] = "IconOutlinedPool";

export const IconOutlinedPool = toNewsKitIcon(Pool);
