// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatAlignJustify} from '@emotion-icons/material/FormatAlignJustify';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatAlignJustify['displayName'] = "IconOutlinedFormatAlignJustify";

export const IconOutlinedFormatAlignJustify = toNewsKitIcon(FormatAlignJustify);
