// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SwitchRight} from '@emotion-icons/material/SwitchRight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SwitchRight.displayName = 'IconOutlinedSwitchRight';

export const IconOutlinedSwitchRight = toNewsKitIcon(SwitchRight);
