// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MergeType} from '@emotion-icons/material/MergeType';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MergeType['displayName'] = "IconOutlinedMergeType";

export const IconOutlinedMergeType = toNewsKitIcon(MergeType);
