// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocationSearching} from '@emotion-icons/material/LocationSearching';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocationSearching.displayName = 'IconOutlinedLocationSearching';

export const IconOutlinedLocationSearching = toNewsKitIcon(LocationSearching);
