// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatIndentIncrease} from '@emotion-icons/material/FormatIndentIncrease';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatIndentIncrease.displayName = 'IconOutlinedFormatIndentIncrease';

export const IconOutlinedFormatIndentIncrease = toNewsKitIcon(
  FormatIndentIncrease,
);
