// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SkipNext} from '@emotion-icons/material/SkipNext';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SkipNext['displayName'] = "IconOutlinedSkipNext";

export const IconOutlinedSkipNext = toNewsKitIcon(SkipNext);
