// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatItalic} from '@emotion-icons/material/FormatItalic';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatItalic['displayName'] = "IconOutlinedFormatItalic";

export const IconOutlinedFormatItalic = toNewsKitIcon(FormatItalic);
