// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MicNone} from '@emotion-icons/material/MicNone';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MicNone.displayName = 'IconOutlinedMicNone';

export const IconOutlinedMicNone = toNewsKitIcon(MicNone);
