// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExpandLess} from '@emotion-icons/material/ExpandLess';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ExpandLess.displayName = 'IconOutlinedExpandLess';

export const IconOutlinedExpandLess = toNewsKitIcon(ExpandLess);
