// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MoreHoriz} from '@emotion-icons/material/MoreHoriz';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
MoreHoriz['displayName'] = "IconOutlinedMoreHoriz";

export const IconOutlinedMoreHoriz = toNewsKitIcon(MoreHoriz);
