// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BrandingWatermark} from '@emotion-icons/material/BrandingWatermark';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BrandingWatermark['displayName'] = "IconOutlinedBrandingWatermark";

export const IconOutlinedBrandingWatermark = toNewsKitIcon(BrandingWatermark);
