// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TransferWithinAStation} from '@emotion-icons/material/TransferWithinAStation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TransferWithinAStation['displayName'] = "IconOutlinedTransferWithinAStation";

export const IconOutlinedTransferWithinAStation = toNewsKitIcon(TransferWithinAStation);
