// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Height} from '@emotion-icons/material/Height';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Height['displayName'] = "IconOutlinedHeight";

export const IconOutlinedHeight = toNewsKitIcon(Height);
