// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StrikethroughS} from '@emotion-icons/material/StrikethroughS';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
StrikethroughS.displayName = 'IconOutlinedStrikethroughS';

export const IconOutlinedStrikethroughS = toNewsKitIcon(StrikethroughS);
