// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PanoramaWideAngle} from '@emotion-icons/material/PanoramaWideAngle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PanoramaWideAngle.displayName = 'IconOutlinedPanoramaWideAngle';

export const IconOutlinedPanoramaWideAngle = toNewsKitIcon(PanoramaWideAngle);
