// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Delete} from '@emotion-icons/material/Delete';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Delete.displayName = 'IconOutlinedDelete';

export const IconOutlinedDelete = toNewsKitIcon(Delete);
