// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EditLocation} from '@emotion-icons/material/EditLocation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
EditLocation['displayName'] = "IconOutlinedEditLocation";

export const IconOutlinedEditLocation = toNewsKitIcon(EditLocation);
