// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Subscriptions} from '@emotion-icons/material/Subscriptions';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Subscriptions['displayName'] = "IconOutlinedSubscriptions";

export const IconOutlinedSubscriptions = toNewsKitIcon(Subscriptions);
