// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhotoLibrary} from '@emotion-icons/material/PhotoLibrary';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PhotoLibrary['displayName'] = "IconOutlinedPhotoLibrary";

export const IconOutlinedPhotoLibrary = toNewsKitIcon(PhotoLibrary);
