// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StickyNote2} from '@emotion-icons/material/StickyNote2';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
StickyNote2.displayName = 'IconOutlinedStickyNote2';

export const IconOutlinedStickyNote2 = toNewsKitIcon(StickyNote2);
