// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Computer} from '@emotion-icons/material/Computer';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Computer.displayName = 'IconOutlinedComputer';

export const IconOutlinedComputer = toNewsKitIcon(Computer);
