// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HelpOutline} from '@emotion-icons/material/HelpOutline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HelpOutline['displayName'] = "IconOutlinedHelpOutline";

export const IconOutlinedHelpOutline = toNewsKitIcon(HelpOutline);
