// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Commute} from '@emotion-icons/material/Commute';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Commute.displayName = 'IconOutlinedCommute';

export const IconOutlinedCommute = toNewsKitIcon(Commute);
