// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Save} from '@emotion-icons/material/Save';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Save.displayName = 'IconOutlinedSave';

export const IconOutlinedSave = toNewsKitIcon(Save);
