// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Tram} from '@emotion-icons/material/Tram';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Tram.displayName = 'IconOutlinedTram';

export const IconOutlinedTram = toNewsKitIcon(Tram);
