// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsSoccer} from '@emotion-icons/material/SportsSoccer';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SportsSoccer['displayName'] = "IconOutlinedSportsSoccer";

export const IconOutlinedSportsSoccer = toNewsKitIcon(SportsSoccer);
