// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalParking} from '@emotion-icons/material/LocalParking';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalParking['displayName'] = "IconOutlinedLocalParking";

export const IconOutlinedLocalParking = toNewsKitIcon(LocalParking);
