// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TvOff} from '@emotion-icons/material/TvOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TvOff.displayName = 'IconOutlinedTvOff';

export const IconOutlinedTvOff = toNewsKitIcon(TvOff);
