// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Foundation} from '@emotion-icons/material/Foundation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Foundation['displayName'] = "IconOutlinedFoundation";

export const IconOutlinedFoundation = toNewsKitIcon(Foundation);
