// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TimerOff} from '@emotion-icons/material/TimerOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TimerOff.displayName = 'IconOutlinedTimerOff';

export const IconOutlinedTimerOff = toNewsKitIcon(TimerOff);
