// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PersonPinCircle} from '@emotion-icons/material/PersonPinCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PersonPinCircle.displayName = 'IconOutlinedPersonPinCircle';

export const IconOutlinedPersonPinCircle = toNewsKitIcon(PersonPinCircle);
