// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {GroupWork} from '@emotion-icons/material/GroupWork';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
GroupWork['displayName'] = "IconOutlinedGroupWork";

export const IconOutlinedGroupWork = toNewsKitIcon(GroupWork);
