// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Functions} from '@emotion-icons/material/Functions';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Functions.displayName = 'IconOutlinedFunctions';

export const IconOutlinedFunctions = toNewsKitIcon(Functions);
