// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SwitchVideo} from '@emotion-icons/material/SwitchVideo';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SwitchVideo['displayName'] = "IconOutlinedSwitchVideo";

export const IconOutlinedSwitchVideo = toNewsKitIcon(SwitchVideo);
