// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DynamicForm} from '@emotion-icons/material/DynamicForm';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DynamicForm['displayName'] = "IconOutlinedDynamicForm";

export const IconOutlinedDynamicForm = toNewsKitIcon(DynamicForm);
