// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Slideshow} from '@emotion-icons/material/Slideshow';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Slideshow['displayName'] = "IconOutlinedSlideshow";

export const IconOutlinedSlideshow = toNewsKitIcon(Slideshow);
