// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DragIndicator} from '@emotion-icons/material/DragIndicator';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DragIndicator.displayName = 'IconOutlinedDragIndicator';

export const IconOutlinedDragIndicator = toNewsKitIcon(DragIndicator);
