// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VisibilityOff} from '@emotion-icons/material/VisibilityOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
VisibilityOff['displayName'] = "IconOutlinedVisibilityOff";

export const IconOutlinedVisibilityOff = toNewsKitIcon(VisibilityOff);
