// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PublicOff} from '@emotion-icons/material/PublicOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PublicOff['displayName'] = "IconOutlinedPublicOff";

export const IconOutlinedPublicOff = toNewsKitIcon(PublicOff);
