// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CropPortrait} from '@emotion-icons/material/CropPortrait';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CropPortrait['displayName'] = "IconOutlinedCropPortrait";

export const IconOutlinedCropPortrait = toNewsKitIcon(CropPortrait);
