// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Pets} from '@emotion-icons/material/Pets';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Pets.displayName = 'IconOutlinedPets';

export const IconOutlinedPets = toNewsKitIcon(Pets);
