// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {InsertChartOutlined} from '@emotion-icons/material/InsertChartOutlined';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
InsertChartOutlined.displayName = 'IconOutlinedInsertChartOutlined';

export const IconOutlinedInsertChartOutlined = toNewsKitIcon(
  InsertChartOutlined,
);
