// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Forward5} from '@emotion-icons/material/Forward5';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Forward5['displayName'] = "IconOutlinedForward5";

export const IconOutlinedForward5 = toNewsKitIcon(Forward5);
