// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DeviceHub} from '@emotion-icons/material/DeviceHub';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DeviceHub.displayName = 'IconOutlinedDeviceHub';

export const IconOutlinedDeviceHub = toNewsKitIcon(DeviceHub);
