// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FamilyRestroom} from '@emotion-icons/material/FamilyRestroom';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FamilyRestroom['displayName'] = "IconOutlinedFamilyRestroom";

export const IconOutlinedFamilyRestroom = toNewsKitIcon(FamilyRestroom);
