// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Eco} from '@emotion-icons/material/Eco';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Eco.displayName = 'IconOutlinedEco';

export const IconOutlinedEco = toNewsKitIcon(Eco);
