// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DeleteForever} from '@emotion-icons/material/DeleteForever';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DeleteForever['displayName'] = "IconOutlinedDeleteForever";

export const IconOutlinedDeleteForever = toNewsKitIcon(DeleteForever);
