// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LockOpen} from '@emotion-icons/material/LockOpen';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LockOpen['displayName'] = "IconOutlinedLockOpen";

export const IconOutlinedLockOpen = toNewsKitIcon(LockOpen);
