// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowDropUp} from '@emotion-icons/material/ArrowDropUp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ArrowDropUp.displayName = 'IconOutlinedArrowDropUp';

export const IconOutlinedArrowDropUp = toNewsKitIcon(ArrowDropUp);
