// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsEsports} from '@emotion-icons/material/SportsEsports';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SportsEsports.displayName = 'IconOutlinedSportsEsports';

export const IconOutlinedSportsEsports = toNewsKitIcon(SportsEsports);
