// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LastPage} from '@emotion-icons/material/LastPage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LastPage['displayName'] = "IconOutlinedLastPage";

export const IconOutlinedLastPage = toNewsKitIcon(LastPage);
