// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Domain} from '@emotion-icons/material/Domain';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Domain.displayName = 'IconOutlinedDomain';

export const IconOutlinedDomain = toNewsKitIcon(Domain);
