// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BluetoothAudio} from '@emotion-icons/material/BluetoothAudio';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BluetoothAudio.displayName = 'IconOutlinedBluetoothAudio';

export const IconOutlinedBluetoothAudio = toNewsKitIcon(BluetoothAudio);
