// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatTextdirectionLToR} from '@emotion-icons/material/FormatTextdirectionLToR';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatTextdirectionLToR['displayName'] = "IconOutlinedFormatTextdirectionLToR";

export const IconOutlinedFormatTextdirectionLToR = toNewsKitIcon(FormatTextdirectionLToR);
