// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Elevator} from '@emotion-icons/material/Elevator';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Elevator.displayName = 'IconOutlinedElevator';

export const IconOutlinedElevator = toNewsKitIcon(Elevator);
