// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Forum} from '@emotion-icons/material/Forum';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Forum.displayName = 'IconOutlinedForum';

export const IconOutlinedForum = toNewsKitIcon(Forum);
