// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Restore} from '@emotion-icons/material/Restore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Restore['displayName'] = "IconOutlinedRestore";

export const IconOutlinedRestore = toNewsKitIcon(Restore);
