// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Wysiwyg} from '@emotion-icons/material/Wysiwyg';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Wysiwyg.displayName = 'IconOutlinedWysiwyg';

export const IconOutlinedWysiwyg = toNewsKitIcon(Wysiwyg);
