// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Dns} from '@emotion-icons/material/Dns';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Dns['displayName'] = "IconOutlinedDns";

export const IconOutlinedDns = toNewsKitIcon(Dns);
