// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AltRoute} from '@emotion-icons/material/AltRoute';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AltRoute.displayName = 'IconOutlinedAltRoute';

export const IconOutlinedAltRoute = toNewsKitIcon(AltRoute);
