// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ShoppingBag} from '@emotion-icons/material/ShoppingBag';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ShoppingBag['displayName'] = "IconOutlinedShoppingBag";

export const IconOutlinedShoppingBag = toNewsKitIcon(ShoppingBag);
