// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SignalCellularConnectedNoInternet4Bar} from '@emotion-icons/material/SignalCellularConnectedNoInternet4Bar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SignalCellularConnectedNoInternet4Bar['displayName'] = "IconOutlinedSignalCellularConnectedNoInternet4Bar";

export const IconOutlinedSignalCellularConnectedNoInternet4Bar = toNewsKitIcon(SignalCellularConnectedNoInternet4Bar);
