// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TableRows} from '@emotion-icons/material/TableRows';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TableRows.displayName = 'IconOutlinedTableRows';

export const IconOutlinedTableRows = toNewsKitIcon(TableRows);
