// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Outlet} from '@emotion-icons/material/Outlet';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Outlet.displayName = 'IconOutlinedOutlet';

export const IconOutlinedOutlet = toNewsKitIcon(Outlet);
