// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CenterFocusWeak} from '@emotion-icons/material/CenterFocusWeak';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CenterFocusWeak.displayName = 'IconOutlinedCenterFocusWeak';

export const IconOutlinedCenterFocusWeak = toNewsKitIcon(CenterFocusWeak);
