// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalMovies} from '@emotion-icons/material/LocalMovies';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LocalMovies.displayName = 'IconFilledLocalMovies';

export const IconFilledLocalMovies = toNewsKitIcon(LocalMovies);
