// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StopCircle} from '@emotion-icons/material/StopCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
StopCircle.displayName = 'IconFilledStopCircle';

export const IconFilledStopCircle = toNewsKitIcon(StopCircle);
