// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Note} from '@emotion-icons/material/Note';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Note['displayName'] = "IconFilledNote";

export const IconFilledNote = toNewsKitIcon(Note);
