// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CropDin} from '@emotion-icons/material/CropDin';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CropDin['displayName'] = "IconFilledCropDin";

export const IconFilledCropDin = toNewsKitIcon(CropDin);
