// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CleanHands} from '@emotion-icons/material/CleanHands';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
CleanHands.displayName = 'IconFilledCleanHands';

export const IconFilledCleanHands = toNewsKitIcon(CleanHands);
