// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Score} from '@emotion-icons/material/Score';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Score.displayName = 'IconFilledScore';

export const IconFilledScore = toNewsKitIcon(Score);
