// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalLaundryService} from '@emotion-icons/material/LocalLaundryService';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalLaundryService['displayName'] = "IconFilledLocalLaundryService";

export const IconFilledLocalLaundryService = toNewsKitIcon(LocalLaundryService);
