// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PriorityHigh} from '@emotion-icons/material/PriorityHigh';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PriorityHigh.displayName = 'IconFilledPriorityHigh';

export const IconFilledPriorityHigh = toNewsKitIcon(PriorityHigh);
