// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PersonAddAlt1} from '@emotion-icons/material/PersonAddAlt1';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PersonAddAlt1.displayName = 'IconFilledPersonAddAlt1';

export const IconFilledPersonAddAlt1 = toNewsKitIcon(PersonAddAlt1);
