// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SensorDoor} from '@emotion-icons/material/SensorDoor';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SensorDoor.displayName = 'IconFilledSensorDoor';

export const IconFilledSensorDoor = toNewsKitIcon(SensorDoor);
