// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Unarchive} from '@emotion-icons/material/Unarchive';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Unarchive.displayName = 'IconFilledUnarchive';

export const IconFilledUnarchive = toNewsKitIcon(Unarchive);
