// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Filter5} from '@emotion-icons/material/Filter5';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Filter5.displayName = 'IconFilledFilter5';

export const IconFilledFilter5 = toNewsKitIcon(Filter5);
