// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Euro} from '@emotion-icons/material/Euro';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Euro.displayName = 'IconFilledEuro';

export const IconFilledEuro = toNewsKitIcon(Euro);
