// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsInputHdmi} from '@emotion-icons/material/SettingsInputHdmi';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsInputHdmi['displayName'] = "IconFilledSettingsInputHdmi";

export const IconFilledSettingsInputHdmi = toNewsKitIcon(SettingsInputHdmi);
