// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Looks6} from '@emotion-icons/material/Looks6';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Looks6['displayName'] = "IconFilledLooks6";

export const IconFilledLooks6 = toNewsKitIcon(Looks6);
