// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Backup} from '@emotion-icons/material/Backup';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Backup['displayName'] = "IconFilledBackup";

export const IconFilledBackup = toNewsKitIcon(Backup);
