// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ContactPhone} from '@emotion-icons/material/ContactPhone';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ContactPhone['displayName'] = "IconFilledContactPhone";

export const IconFilledContactPhone = toNewsKitIcon(ContactPhone);
