// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Today} from '@emotion-icons/material/Today';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Today.displayName = 'IconFilledToday';

export const IconFilledToday = toNewsKitIcon(Today);
