// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Event} from '@emotion-icons/material/Event';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Event.displayName = 'IconFilledEvent';

export const IconFilledEvent = toNewsKitIcon(Event);
