// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TextRotateVertical} from '@emotion-icons/material/TextRotateVertical';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TextRotateVertical['displayName'] = "IconFilledTextRotateVertical";

export const IconFilledTextRotateVertical = toNewsKitIcon(TextRotateVertical);
