// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Extension} from '@emotion-icons/material/Extension';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Extension.displayName = 'IconFilledExtension';

export const IconFilledExtension = toNewsKitIcon(Extension);
