// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Timeline} from '@emotion-icons/material/Timeline';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Timeline['displayName'] = "IconFilledTimeline";

export const IconFilledTimeline = toNewsKitIcon(Timeline);
