// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Verified} from '@emotion-icons/material/Verified';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Verified['displayName'] = "IconFilledVerified";

export const IconFilledVerified = toNewsKitIcon(Verified);
