// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VoiceOverOff} from '@emotion-icons/material/VoiceOverOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VoiceOverOff.displayName = 'IconFilledVoiceOverOff';

export const IconFilledVoiceOverOff = toNewsKitIcon(VoiceOverOff);
