// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Usb} from '@emotion-icons/material/Usb';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Usb['displayName'] = "IconFilledUsb";

export const IconFilledUsb = toNewsKitIcon(Usb);
