// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PanTool} from '@emotion-icons/material/PanTool';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PanTool['displayName'] = "IconFilledPanTool";

export const IconFilledPanTool = toNewsKitIcon(PanTool);
