// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ImageSearch} from '@emotion-icons/material/ImageSearch';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ImageSearch['displayName'] = "IconFilledImageSearch";

export const IconFilledImageSearch = toNewsKitIcon(ImageSearch);
