// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DesktopMac} from '@emotion-icons/material/DesktopMac';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
DesktopMac.displayName = 'IconFilledDesktopMac';

export const IconFilledDesktopMac = toNewsKitIcon(DesktopMac);
