// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsVoice} from '@emotion-icons/material/SettingsVoice';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SettingsVoice.displayName = 'IconFilledSettingsVoice';

export const IconFilledSettingsVoice = toNewsKitIcon(SettingsVoice);
