// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Money} from '@emotion-icons/material/Money';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Money['displayName'] = "IconFilledMoney";

export const IconFilledMoney = toNewsKitIcon(Money);
