// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LaptopChromebook} from '@emotion-icons/material/LaptopChromebook';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LaptopChromebook.displayName = 'IconFilledLaptopChromebook';

export const IconFilledLaptopChromebook = toNewsKitIcon(LaptopChromebook);
