// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Anchor} from '@emotion-icons/material/Anchor';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Anchor['displayName'] = "IconFilledAnchor";

export const IconFilledAnchor = toNewsKitIcon(Anchor);
