// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatAlignRight} from '@emotion-icons/material/FormatAlignRight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FormatAlignRight.displayName = 'IconFilledFormatAlignRight';

export const IconFilledFormatAlignRight = toNewsKitIcon(FormatAlignRight);
