// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WrapText} from '@emotion-icons/material/WrapText';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
WrapText['displayName'] = "IconFilledWrapText";

export const IconFilledWrapText = toNewsKitIcon(WrapText);
