// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsBus} from '@emotion-icons/material/DirectionsBus';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
DirectionsBus.displayName = 'IconFilledDirectionsBus';

export const IconFilledDirectionsBus = toNewsKitIcon(DirectionsBus);
