// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SentimentVeryDissatisfied} from '@emotion-icons/material/SentimentVeryDissatisfied';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SentimentVeryDissatisfied.displayName = 'IconFilledSentimentVeryDissatisfied';

export const IconFilledSentimentVeryDissatisfied = toNewsKitIcon(
  SentimentVeryDissatisfied,
);
