// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ColorLens} from '@emotion-icons/material/ColorLens';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ColorLens['displayName'] = "IconFilledColorLens";

export const IconFilledColorLens = toNewsKitIcon(ColorLens);
