// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowCircleDown} from '@emotion-icons/material/ArrowCircleDown';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ArrowCircleDown.displayName = 'IconFilledArrowCircleDown';

export const IconFilledArrowCircleDown = toNewsKitIcon(ArrowCircleDown);
