// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MiscellaneousServices} from '@emotion-icons/material/MiscellaneousServices';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
MiscellaneousServices.displayName = 'IconFilledMiscellaneousServices';

export const IconFilledMiscellaneousServices = toNewsKitIcon(
  MiscellaneousServices,
);
