// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Language} from '@emotion-icons/material/Language';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Language.displayName = 'IconFilledLanguage';

export const IconFilledLanguage = toNewsKitIcon(Language);
