// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Face} from '@emotion-icons/material/Face';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Face.displayName = 'IconFilledFace';

export const IconFilledFace = toNewsKitIcon(Face);
