// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Redeem} from '@emotion-icons/material/Redeem';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Redeem['displayName'] = "IconFilledRedeem";

export const IconFilledRedeem = toNewsKitIcon(Redeem);
