// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FlipCameraAndroid} from '@emotion-icons/material/FlipCameraAndroid';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FlipCameraAndroid.displayName = 'IconFilledFlipCameraAndroid';

export const IconFilledFlipCameraAndroid = toNewsKitIcon(FlipCameraAndroid);
