// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EnhancedEncryption} from '@emotion-icons/material/EnhancedEncryption';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
EnhancedEncryption.displayName = 'IconFilledEnhancedEncryption';

export const IconFilledEnhancedEncryption = toNewsKitIcon(EnhancedEncryption);
