// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AccessAlarm} from '@emotion-icons/material/AccessAlarm';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AccessAlarm['displayName'] = "IconFilledAccessAlarm";

export const IconFilledAccessAlarm = toNewsKitIcon(AccessAlarm);
