// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PowerInput} from '@emotion-icons/material/PowerInput';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PowerInput.displayName = 'IconFilledPowerInput';

export const IconFilledPowerInput = toNewsKitIcon(PowerInput);
