// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RequestQuote} from '@emotion-icons/material/RequestQuote';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
RequestQuote.displayName = 'IconFilledRequestQuote';

export const IconFilledRequestQuote = toNewsKitIcon(RequestQuote);
