// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VideoLibrary} from '@emotion-icons/material/VideoLibrary';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VideoLibrary.displayName = 'IconFilledVideoLibrary';

export const IconFilledVideoLibrary = toNewsKitIcon(VideoLibrary);
