// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Escalator} from '@emotion-icons/material/Escalator';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Escalator['displayName'] = "IconFilledEscalator";

export const IconFilledEscalator = toNewsKitIcon(Escalator);
