// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DirectionsCar} from '@emotion-icons/material/DirectionsCar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DirectionsCar['displayName'] = "IconFilledDirectionsCar";

export const IconFilledDirectionsCar = toNewsKitIcon(DirectionsCar);
