// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Devices} from '@emotion-icons/material/Devices';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Devices.displayName = 'IconFilledDevices';

export const IconFilledDevices = toNewsKitIcon(Devices);
