// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NotStarted} from '@emotion-icons/material/NotStarted';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
NotStarted.displayName = 'IconFilledNotStarted';

export const IconFilledNotStarted = toNewsKitIcon(NotStarted);
