// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TextFormat} from '@emotion-icons/material/TextFormat';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
TextFormat.displayName = 'IconFilledTextFormat';

export const IconFilledTextFormat = toNewsKitIcon(TextFormat);
