// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {OpenInFull} from '@emotion-icons/material/OpenInFull';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
OpenInFull.displayName = 'IconFilledOpenInFull';

export const IconFilledOpenInFull = toNewsKitIcon(OpenInFull);
