// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ChargingStation} from '@emotion-icons/material/ChargingStation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ChargingStation['displayName'] = "IconFilledChargingStation";

export const IconFilledChargingStation = toNewsKitIcon(ChargingStation);
