// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Filter3} from '@emotion-icons/material/Filter3';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Filter3.displayName = 'IconFilledFilter3';

export const IconFilledFilter3 = toNewsKitIcon(Filter3);
