// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VerticalAlignCenter} from '@emotion-icons/material/VerticalAlignCenter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VerticalAlignCenter.displayName = 'IconFilledVerticalAlignCenter';

export const IconFilledVerticalAlignCenter = toNewsKitIcon(VerticalAlignCenter);
