// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FeaturedVideo} from '@emotion-icons/material/FeaturedVideo';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FeaturedVideo.displayName = 'IconFilledFeaturedVideo';

export const IconFilledFeaturedVideo = toNewsKitIcon(FeaturedVideo);
