// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BugReport} from '@emotion-icons/material/BugReport';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BugReport['displayName'] = "IconFilledBugReport";

export const IconFilledBugReport = toNewsKitIcon(BugReport);
