// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FileCopy} from '@emotion-icons/material/FileCopy';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FileCopy.displayName = 'IconFilledFileCopy';

export const IconFilledFileCopy = toNewsKitIcon(FileCopy);
