// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddToHomeScreen} from '@emotion-icons/material/AddToHomeScreen';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AddToHomeScreen['displayName'] = "IconFilledAddToHomeScreen";

export const IconFilledAddToHomeScreen = toNewsKitIcon(AddToHomeScreen);
