// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EmojiEmotions} from '@emotion-icons/material/EmojiEmotions';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
EmojiEmotions.displayName = 'IconFilledEmojiEmotions';

export const IconFilledEmojiEmotions = toNewsKitIcon(EmojiEmotions);
