// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Superscript} from '@emotion-icons/material/Superscript';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Superscript['displayName'] = "IconFilledSuperscript";

export const IconFilledSuperscript = toNewsKitIcon(Superscript);
