// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Image} from '@emotion-icons/material/Image';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Image['displayName'] = "IconFilledImage";

export const IconFilledImage = toNewsKitIcon(Image);
