// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Fence} from '@emotion-icons/material/Fence';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Fence['displayName'] = "IconFilledFence";

export const IconFilledFence = toNewsKitIcon(Fence);
