// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Comment} from '@emotion-icons/material/Comment';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Comment['displayName'] = "IconFilledComment";

export const IconFilledComment = toNewsKitIcon(Comment);
