// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StarHalf} from '@emotion-icons/material/StarHalf';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
StarHalf['displayName'] = "IconFilledStarHalf";

export const IconFilledStarHalf = toNewsKitIcon(StarHalf);
