// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalAirport} from '@emotion-icons/material/LocalAirport';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalAirport['displayName'] = "IconFilledLocalAirport";

export const IconFilledLocalAirport = toNewsKitIcon(LocalAirport);
