// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Wash} from '@emotion-icons/material/Wash';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Wash.displayName = 'IconFilledWash';

export const IconFilledWash = toNewsKitIcon(Wash);
