// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExpandMore} from '@emotion-icons/material/ExpandMore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ExpandMore['displayName'] = "IconFilledExpandMore";

export const IconFilledExpandMore = toNewsKitIcon(ExpandMore);
