// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Microwave} from '@emotion-icons/material/Microwave';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Microwave['displayName'] = "IconFilledMicrowave";

export const IconFilledMicrowave = toNewsKitIcon(Microwave);
