// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {StarBorder} from '@emotion-icons/material/StarBorder';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
StarBorder.displayName = 'IconFilledStarBorder';

export const IconFilledStarBorder = toNewsKitIcon(StarBorder);
