// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Gesture} from '@emotion-icons/material/Gesture';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Gesture.displayName = 'IconFilledGesture';

export const IconFilledGesture = toNewsKitIcon(Gesture);
