// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Info} from '@emotion-icons/material/Info';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Info['displayName'] = "IconFilledInfo";

export const IconFilledInfo = toNewsKitIcon(Info);
