// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PersonAdd} from '@emotion-icons/material/PersonAdd';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PersonAdd.displayName = 'IconFilledPersonAdd';

export const IconFilledPersonAdd = toNewsKitIcon(PersonAdd);
