// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ViewAgenda} from '@emotion-icons/material/ViewAgenda';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ViewAgenda['displayName'] = "IconFilledViewAgenda";

export const IconFilledViewAgenda = toNewsKitIcon(ViewAgenda);
