// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhonelinkErase} from '@emotion-icons/material/PhonelinkErase';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhonelinkErase.displayName = 'IconFilledPhonelinkErase';

export const IconFilledPhonelinkErase = toNewsKitIcon(PhonelinkErase);
