// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Looks} from '@emotion-icons/material/Looks';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Looks.displayName = 'IconFilledLooks';

export const IconFilledLooks = toNewsKitIcon(Looks);
