// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FolderShared} from '@emotion-icons/material/FolderShared';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FolderShared.displayName = 'IconFilledFolderShared';

export const IconFilledFolderShared = toNewsKitIcon(FolderShared);
