// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NotificationsPaused} from '@emotion-icons/material/NotificationsPaused';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NotificationsPaused['displayName'] = "IconFilledNotificationsPaused";

export const IconFilledNotificationsPaused = toNewsKitIcon(NotificationsPaused);
