// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Launch} from '@emotion-icons/material/Launch';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Launch.displayName = 'IconFilledLaunch';

export const IconFilledLaunch = toNewsKitIcon(Launch);
