// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsInputAntenna} from '@emotion-icons/material/SettingsInputAntenna';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SettingsInputAntenna.displayName = 'IconFilledSettingsInputAntenna';

export const IconFilledSettingsInputAntenna = toNewsKitIcon(
  SettingsInputAntenna,
);
