// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BlurLinear} from '@emotion-icons/material/BlurLinear';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
BlurLinear.displayName = 'IconFilledBlurLinear';

export const IconFilledBlurLinear = toNewsKitIcon(BlurLinear);
