// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ImportantDevices} from '@emotion-icons/material/ImportantDevices';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ImportantDevices['displayName'] = "IconFilledImportantDevices";

export const IconFilledImportantDevices = toNewsKitIcon(ImportantDevices);
