// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Replay10} from '@emotion-icons/material/Replay10';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Replay10['displayName'] = "IconFilledReplay10";

export const IconFilledReplay10 = toNewsKitIcon(Replay10);
