// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VerticalAlignTop} from '@emotion-icons/material/VerticalAlignTop';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VerticalAlignTop.displayName = 'IconFilledVerticalAlignTop';

export const IconFilledVerticalAlignTop = toNewsKitIcon(VerticalAlignTop);
