// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalTaxi} from '@emotion-icons/material/LocalTaxi';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalTaxi['displayName'] = "IconFilledLocalTaxi";

export const IconFilledLocalTaxi = toNewsKitIcon(LocalTaxi);
