// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MobileOff} from '@emotion-icons/material/MobileOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
MobileOff.displayName = 'IconFilledMobileOff';

export const IconFilledMobileOff = toNewsKitIcon(MobileOff);
