// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DoneAll} from '@emotion-icons/material/DoneAll';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DoneAll['displayName'] = "IconFilledDoneAll";

export const IconFilledDoneAll = toNewsKitIcon(DoneAll);
