// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ViewSidebar} from '@emotion-icons/material/ViewSidebar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ViewSidebar['displayName'] = "IconFilledViewSidebar";

export const IconFilledViewSidebar = toNewsKitIcon(ViewSidebar);
