// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BatteryUnknown} from '@emotion-icons/material/BatteryUnknown';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
BatteryUnknown.displayName = 'IconFilledBatteryUnknown';

export const IconFilledBatteryUnknown = toNewsKitIcon(BatteryUnknown);
