// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NoCell} from '@emotion-icons/material/NoCell';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
NoCell.displayName = 'IconFilledNoCell';

export const IconFilledNoCell = toNewsKitIcon(NoCell);
