// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhoneForwarded} from '@emotion-icons/material/PhoneForwarded';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhoneForwarded.displayName = 'IconFilledPhoneForwarded';

export const IconFilledPhoneForwarded = toNewsKitIcon(PhoneForwarded);
