// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FiberDvr} from '@emotion-icons/material/FiberDvr';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FiberDvr.displayName = 'IconFilledFiberDvr';

export const IconFilledFiberDvr = toNewsKitIcon(FiberDvr);
