// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CloudOff} from '@emotion-icons/material/CloudOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
CloudOff.displayName = 'IconFilledCloudOff';

export const IconFilledCloudOff = toNewsKitIcon(CloudOff);
