// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Pageview} from '@emotion-icons/material/Pageview';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Pageview.displayName = 'IconFilledPageview';

export const IconFilledPageview = toNewsKitIcon(Pageview);
