// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PanoramaVertical} from '@emotion-icons/material/PanoramaVertical';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PanoramaVertical['displayName'] = "IconFilledPanoramaVertical";

export const IconFilledPanoramaVertical = toNewsKitIcon(PanoramaVertical);
