// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Campaign} from '@emotion-icons/material/Campaign';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Campaign['displayName'] = "IconFilledCampaign";

export const IconFilledCampaign = toNewsKitIcon(Campaign);
