// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FolderOpen} from '@emotion-icons/material/FolderOpen';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FolderOpen.displayName = 'IconFilledFolderOpen';

export const IconFilledFolderOpen = toNewsKitIcon(FolderOpen);
