// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Grain} from '@emotion-icons/material/Grain';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Grain.displayName = 'IconFilledGrain';

export const IconFilledGrain = toNewsKitIcon(Grain);
