// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {InsertPhoto} from '@emotion-icons/material/InsertPhoto';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
InsertPhoto.displayName = 'IconFilledInsertPhoto';

export const IconFilledInsertPhoto = toNewsKitIcon(InsertPhoto);
