// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WbAuto} from '@emotion-icons/material/WbAuto';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
WbAuto['displayName'] = "IconFilledWbAuto";

export const IconFilledWbAuto = toNewsKitIcon(WbAuto);
