// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WineBar} from '@emotion-icons/material/WineBar';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
WineBar.displayName = 'IconFilledWineBar';

export const IconFilledWineBar = toNewsKitIcon(WineBar);
