// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Cast} from '@emotion-icons/material/Cast';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Cast['displayName'] = "IconFilledCast";

export const IconFilledCast = toNewsKitIcon(Cast);
