// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExposurePlus1} from '@emotion-icons/material/ExposurePlus1';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ExposurePlus1.displayName = 'IconFilledExposurePlus1';

export const IconFilledExposurePlus1 = toNewsKitIcon(ExposurePlus1);
