// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Close} from '@emotion-icons/material/Close';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Close['displayName'] = "IconFilledClose";

export const IconFilledClose = toNewsKitIcon(Close);
