// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SmsFailed} from '@emotion-icons/material/SmsFailed';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SmsFailed.displayName = 'IconFilledSmsFailed';

export const IconFilledSmsFailed = toNewsKitIcon(SmsFailed);
