// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RestaurantMenu} from '@emotion-icons/material/RestaurantMenu';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RestaurantMenu['displayName'] = "IconFilledRestaurantMenu";

export const IconFilledRestaurantMenu = toNewsKitIcon(RestaurantMenu);
