// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MarkEmailRead} from '@emotion-icons/material/MarkEmailRead';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
MarkEmailRead.displayName = 'IconFilledMarkEmailRead';

export const IconFilledMarkEmailRead = toNewsKitIcon(MarkEmailRead);
