// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DoubleArrow} from '@emotion-icons/material/DoubleArrow';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DoubleArrow['displayName'] = "IconFilledDoubleArrow";

export const IconFilledDoubleArrow = toNewsKitIcon(DoubleArrow);
