// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MultilineChart} from '@emotion-icons/material/MultilineChart';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
MultilineChart.displayName = 'IconFilledMultilineChart';

export const IconFilledMultilineChart = toNewsKitIcon(MultilineChart);
