// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FourK} from '@emotion-icons/material/FourK';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FourK.displayName = 'IconFilledFourK';

export const IconFilledFourK = toNewsKitIcon(FourK);
