// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {History} from '@emotion-icons/material/History';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
History.displayName = 'IconFilledHistory';

export const IconFilledHistory = toNewsKitIcon(History);
