// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatListNumbered} from '@emotion-icons/material/FormatListNumbered';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatListNumbered['displayName'] = "IconFilledFormatListNumbered";

export const IconFilledFormatListNumbered = toNewsKitIcon(FormatListNumbered);
