// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FeaturedPlayList} from '@emotion-icons/material/FeaturedPlayList';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FeaturedPlayList.displayName = 'IconFilledFeaturedPlayList';

export const IconFilledFeaturedPlayList = toNewsKitIcon(FeaturedPlayList);
