// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Receipt} from '@emotion-icons/material/Receipt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Receipt['displayName'] = "IconFilledReceipt";

export const IconFilledReceipt = toNewsKitIcon(Receipt);
