// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Replay30} from '@emotion-icons/material/Replay30';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Replay30['displayName'] = "IconFilledReplay30";

export const IconFilledReplay30 = toNewsKitIcon(Replay30);
