// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsBrightness} from '@emotion-icons/material/SettingsBrightness';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SettingsBrightness.displayName = 'IconFilledSettingsBrightness';

export const IconFilledSettingsBrightness = toNewsKitIcon(SettingsBrightness);
