// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RoomService} from '@emotion-icons/material/RoomService';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
RoomService.displayName = 'IconFilledRoomService';

export const IconFilledRoomService = toNewsKitIcon(RoomService);
