// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {OfflinePin} from '@emotion-icons/material/OfflinePin';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
OfflinePin['displayName'] = "IconFilledOfflinePin";

export const IconFilledOfflinePin = toNewsKitIcon(OfflinePin);
