// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Public} from '@emotion-icons/material/Public';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Public.displayName = 'IconFilledPublic';

export const IconFilledPublic = toNewsKitIcon(Public);
