// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Filter1} from '@emotion-icons/material/Filter1';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Filter1['displayName'] = "IconFilledFilter1";

export const IconFilledFilter1 = toNewsKitIcon(Filter1);
