// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AccountCircle} from '@emotion-icons/material/AccountCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AccountCircle.displayName = 'IconFilledAccountCircle';

export const IconFilledAccountCircle = toNewsKitIcon(AccountCircle);
