// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FlightTakeoff} from '@emotion-icons/material/FlightTakeoff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FlightTakeoff.displayName = 'IconFilledFlightTakeoff';

export const IconFilledFlightTakeoff = toNewsKitIcon(FlightTakeoff);
