// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Quickreply} from '@emotion-icons/material/Quickreply';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Quickreply['displayName'] = "IconFilledQuickreply";

export const IconFilledQuickreply = toNewsKitIcon(Quickreply);
