// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Payment} from '@emotion-icons/material/Payment';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Payment.displayName = 'IconFilledPayment';

export const IconFilledPayment = toNewsKitIcon(Payment);
