// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Http} from '@emotion-icons/material/Http';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Http['displayName'] = "IconFilledHttp";

export const IconFilledHttp = toNewsKitIcon(Http);
