// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowLeft} from '@emotion-icons/material/ArrowLeft';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ArrowLeft.displayName = 'IconFilledArrowLeft';

export const IconFilledArrowLeft = toNewsKitIcon(ArrowLeft);
