// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatLineSpacing} from '@emotion-icons/material/FormatLineSpacing';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FormatLineSpacing['displayName'] = "IconFilledFormatLineSpacing";

export const IconFilledFormatLineSpacing = toNewsKitIcon(FormatLineSpacing);
