// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AssignmentReturn} from '@emotion-icons/material/AssignmentReturn';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AssignmentReturn['displayName'] = "IconFilledAssignmentReturn";

export const IconFilledAssignmentReturn = toNewsKitIcon(AssignmentReturn);
