// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Carpenter} from '@emotion-icons/material/Carpenter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Carpenter.displayName = 'IconFilledCarpenter';

export const IconFilledCarpenter = toNewsKitIcon(Carpenter);
