// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EditRoad} from '@emotion-icons/material/EditRoad';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
EditRoad.displayName = 'IconFilledEditRoad';

export const IconFilledEditRoad = toNewsKitIcon(EditRoad);
