// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {GolfCourse} from '@emotion-icons/material/GolfCourse';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
GolfCourse.displayName = 'IconFilledGolfCourse';

export const IconFilledGolfCourse = toNewsKitIcon(GolfCourse);
