// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Transform} from '@emotion-icons/material/Transform';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Transform['displayName'] = "IconFilledTransform";

export const IconFilledTransform = toNewsKitIcon(Transform);
