// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Business} from '@emotion-icons/material/Business';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Business.displayName = 'IconFilledBusiness';

export const IconFilledBusiness = toNewsKitIcon(Business);
