// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FlipCameraIos} from '@emotion-icons/material/FlipCameraIos';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FlipCameraIos['displayName'] = "IconFilledFlipCameraIos";

export const IconFilledFlipCameraIos = toNewsKitIcon(FlipCameraIos);
