// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalFlorist} from '@emotion-icons/material/LocalFlorist';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LocalFlorist.displayName = 'IconFilledLocalFlorist';

export const IconFilledLocalFlorist = toNewsKitIcon(LocalFlorist);
