// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Crop54} from '@emotion-icons/material/Crop54';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Crop54.displayName = 'IconFilledCrop54';

export const IconFilledCrop54 = toNewsKitIcon(Crop54);
