// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Headset} from '@emotion-icons/material/Headset';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Headset.displayName = 'IconFilledHeadset';

export const IconFilledHeadset = toNewsKitIcon(Headset);
