// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Hvac} from '@emotion-icons/material/Hvac';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Hvac.displayName = 'IconFilledHvac';

export const IconFilledHvac = toNewsKitIcon(Hvac);
