// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ContentCopy} from '@emotion-icons/material/ContentCopy';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ContentCopy['displayName'] = "IconFilledContentCopy";

export const IconFilledContentCopy = toNewsKitIcon(ContentCopy);
