// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Map} from '@emotion-icons/material/Map';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Map.displayName = 'IconFilledMap';

export const IconFilledMap = toNewsKitIcon(Map);
