// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhonePaused} from '@emotion-icons/material/PhonePaused';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhonePaused.displayName = 'IconFilledPhonePaused';

export const IconFilledPhonePaused = toNewsKitIcon(PhonePaused);
