// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PresentToAll} from '@emotion-icons/material/PresentToAll';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PresentToAll['displayName'] = "IconFilledPresentToAll";

export const IconFilledPresentToAll = toNewsKitIcon(PresentToAll);
