// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Pending} from '@emotion-icons/material/Pending';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Pending.displayName = 'IconFilledPending';

export const IconFilledPending = toNewsKitIcon(Pending);
