// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CheckCircle} from '@emotion-icons/material/CheckCircle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CheckCircle['displayName'] = "IconFilledCheckCircle";

export const IconFilledCheckCircle = toNewsKitIcon(CheckCircle);
