// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Source} from '@emotion-icons/material/Source';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Source['displayName'] = "IconFilledSource";

export const IconFilledSource = toNewsKitIcon(Source);
