// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Subject} from '@emotion-icons/material/Subject';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Subject['displayName'] = "IconFilledSubject";

export const IconFilledSubject = toNewsKitIcon(Subject);
