// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Power} from '@emotion-icons/material/Power';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Power['displayName'] = "IconFilledPower";

export const IconFilledPower = toNewsKitIcon(Power);
