// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EmojiPeople} from '@emotion-icons/material/EmojiPeople';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
EmojiPeople.displayName = 'IconFilledEmojiPeople';

export const IconFilledEmojiPeople = toNewsKitIcon(EmojiPeople);
