// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Tab} from '@emotion-icons/material/Tab';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Tab.displayName = 'IconFilledTab';

export const IconFilledTab = toNewsKitIcon(Tab);
