// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DepartureBoard} from '@emotion-icons/material/DepartureBoard';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
DepartureBoard['displayName'] = "IconFilledDepartureBoard";

export const IconFilledDepartureBoard = toNewsKitIcon(DepartureBoard);
