// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WatchLater} from '@emotion-icons/material/WatchLater';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
WatchLater.displayName = 'IconFilledWatchLater';

export const IconFilledWatchLater = toNewsKitIcon(WatchLater);
