// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalGroceryStore} from '@emotion-icons/material/LocalGroceryStore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
LocalGroceryStore['displayName'] = "IconFilledLocalGroceryStore";

export const IconFilledLocalGroceryStore = toNewsKitIcon(LocalGroceryStore);
