// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SensorWindow} from '@emotion-icons/material/SensorWindow';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SensorWindow['displayName'] = "IconFilledSensorWindow";

export const IconFilledSensorWindow = toNewsKitIcon(SensorWindow);
