// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ElectricMoped} from '@emotion-icons/material/ElectricMoped';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ElectricMoped.displayName = 'IconFilledElectricMoped';

export const IconFilledElectricMoped = toNewsKitIcon(ElectricMoped);
