// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PlusOne} from '@emotion-icons/material/PlusOne';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PlusOne.displayName = 'IconFilledPlusOne';

export const IconFilledPlusOne = toNewsKitIcon(PlusOne);
