// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Report} from '@emotion-icons/material/Report';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Report['displayName'] = "IconFilledReport";

export const IconFilledReport = toNewsKitIcon(Report);
