// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ScreenLockPortrait} from '@emotion-icons/material/ScreenLockPortrait';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ScreenLockPortrait.displayName = 'IconFilledScreenLockPortrait';

export const IconFilledScreenLockPortrait = toNewsKitIcon(ScreenLockPortrait);
