// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NotInterested} from '@emotion-icons/material/NotInterested';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
NotInterested['displayName'] = "IconFilledNotInterested";

export const IconFilledNotInterested = toNewsKitIcon(NotInterested);
