// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExposurePlus2} from '@emotion-icons/material/ExposurePlus2';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ExposurePlus2['displayName'] = "IconFilledExposurePlus2";

export const IconFilledExposurePlus2 = toNewsKitIcon(ExposurePlus2);
