// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalPizza} from '@emotion-icons/material/LocalPizza';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LocalPizza.displayName = 'IconFilledLocalPizza';

export const IconFilledLocalPizza = toNewsKitIcon(LocalPizza);
