// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Looks3} from '@emotion-icons/material/Looks3';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Looks3['displayName'] = "IconFilledLooks3";

export const IconFilledLooks3 = toNewsKitIcon(Looks3);
