// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Error} from '@emotion-icons/material/Error';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Error['displayName'] = "IconFilledError";

export const IconFilledError = toNewsKitIcon(Error);
