// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AccountBalanceWallet} from '@emotion-icons/material/AccountBalanceWallet';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
AccountBalanceWallet['displayName'] = "IconFilledAccountBalanceWallet";

export const IconFilledAccountBalanceWallet = toNewsKitIcon(AccountBalanceWallet);
