// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Fingerprint} from '@emotion-icons/material/Fingerprint';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Fingerprint.displayName = 'IconFilledFingerprint';

export const IconFilledFingerprint = toNewsKitIcon(Fingerprint);
