// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FindInPage} from '@emotion-icons/material/FindInPage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FindInPage['displayName'] = "IconFilledFindInPage";

export const IconFilledFindInPage = toNewsKitIcon(FindInPage);
