// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Reply} from '@emotion-icons/material/Reply';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Reply.displayName = 'IconFilledReply';

export const IconFilledReply = toNewsKitIcon(Reply);
