// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ImportExport} from '@emotion-icons/material/ImportExport';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ImportExport['displayName'] = "IconFilledImportExport";

export const IconFilledImportExport = toNewsKitIcon(ImportExport);
