// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SimCard} from '@emotion-icons/material/SimCard';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SimCard['displayName'] = "IconFilledSimCard";

export const IconFilledSimCard = toNewsKitIcon(SimCard);
