// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {North} from '@emotion-icons/material/North';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
North['displayName'] = "IconFilledNorth";

export const IconFilledNorth = toNewsKitIcon(North);
