// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CallSplit} from '@emotion-icons/material/CallSplit';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CallSplit['displayName'] = "IconFilledCallSplit";

export const IconFilledCallSplit = toNewsKitIcon(CallSplit);
