// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HighlightAlt} from '@emotion-icons/material/HighlightAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HighlightAlt['displayName'] = "IconFilledHighlightAlt";

export const IconFilledHighlightAlt = toNewsKitIcon(HighlightAlt);
