// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VideoCall} from '@emotion-icons/material/VideoCall';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VideoCall.displayName = 'IconFilledVideoCall';

export const IconFilledVideoCall = toNewsKitIcon(VideoCall);
