// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PlayCircleFilled} from '@emotion-icons/material/PlayCircleFilled';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PlayCircleFilled.displayName = 'IconFilledPlayCircleFilled';

export const IconFilledPlayCircleFilled = toNewsKitIcon(PlayCircleFilled);
