// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BrightnessAuto} from '@emotion-icons/material/BrightnessAuto';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
BrightnessAuto.displayName = 'IconFilledBrightnessAuto';

export const IconFilledBrightnessAuto = toNewsKitIcon(BrightnessAuto);
