// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Autorenew} from '@emotion-icons/material/Autorenew';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Autorenew['displayName'] = "IconFilledAutorenew";

export const IconFilledAutorenew = toNewsKitIcon(Autorenew);
