// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Eject} from '@emotion-icons/material/Eject';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Eject['displayName'] = "IconFilledEject";

export const IconFilledEject = toNewsKitIcon(Eject);
