// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Rowing} from '@emotion-icons/material/Rowing';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Rowing.displayName = 'IconFilledRowing';

export const IconFilledRowing = toNewsKitIcon(Rowing);
