// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddBox} from '@emotion-icons/material/AddBox';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AddBox.displayName = 'IconFilledAddBox';

export const IconFilledAddBox = toNewsKitIcon(AddBox);
