// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LocalConvenienceStore} from '@emotion-icons/material/LocalConvenienceStore';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LocalConvenienceStore.displayName = 'IconFilledLocalConvenienceStore';

export const IconFilledLocalConvenienceStore = toNewsKitIcon(
  LocalConvenienceStore,
);
