// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Plumbing} from '@emotion-icons/material/Plumbing';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Plumbing.displayName = 'IconFilledPlumbing';

export const IconFilledPlumbing = toNewsKitIcon(Plumbing);
