// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SouthEast} from '@emotion-icons/material/SouthEast';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SouthEast.displayName = 'IconFilledSouthEast';

export const IconFilledSouthEast = toNewsKitIcon(SouthEast);
