// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RingVolume} from '@emotion-icons/material/RingVolume';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
RingVolume.displayName = 'IconFilledRingVolume';

export const IconFilledRingVolume = toNewsKitIcon(RingVolume);
