// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FoodBank} from '@emotion-icons/material/FoodBank';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
FoodBank['displayName'] = "IconFilledFoodBank";

export const IconFilledFoodBank = toNewsKitIcon(FoodBank);
