// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CastConnected} from '@emotion-icons/material/CastConnected';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CastConnected['displayName'] = "IconFilledCastConnected";

export const IconFilledCastConnected = toNewsKitIcon(CastConnected);
