// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Palette} from '@emotion-icons/material/Palette';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Palette.displayName = 'IconFilledPalette';

export const IconFilledPalette = toNewsKitIcon(Palette);
