// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BarChart} from '@emotion-icons/material/BarChart';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
BarChart.displayName = 'IconFilledBarChart';

export const IconFilledBarChart = toNewsKitIcon(BarChart);
