// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ControlCamera} from '@emotion-icons/material/ControlCamera';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ControlCamera.displayName = 'IconFilledControlCamera';

export const IconFilledControlCamera = toNewsKitIcon(ControlCamera);
