// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {MarkChatUnread} from '@emotion-icons/material/MarkChatUnread';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
MarkChatUnread.displayName = 'IconFilledMarkChatUnread';

export const IconFilledMarkChatUnread = toNewsKitIcon(MarkChatUnread);
