// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RotateRight} from '@emotion-icons/material/RotateRight';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
RotateRight['displayName'] = "IconFilledRotateRight";

export const IconFilledRotateRight = toNewsKitIcon(RotateRight);
