// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Check} from '@emotion-icons/material/Check';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Check.displayName = 'IconFilledCheck';

export const IconFilledCheck = toNewsKitIcon(Check);
