// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SportsFootball} from '@emotion-icons/material/SportsFootball';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SportsFootball.displayName = 'IconFilledSportsFootball';

export const IconFilledSportsFootball = toNewsKitIcon(SportsFootball);
