// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Waves} from '@emotion-icons/material/Waves';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Waves.displayName = 'IconFilledWaves';

export const IconFilledWaves = toNewsKitIcon(Waves);
