// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {LooksTwo} from '@emotion-icons/material/LooksTwo';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
LooksTwo.displayName = 'IconFilledLooksTwo';

export const IconFilledLooksTwo = toNewsKitIcon(LooksTwo);
