// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhoneIphone} from '@emotion-icons/material/PhoneIphone';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhoneIphone.displayName = 'IconFilledPhoneIphone';

export const IconFilledPhoneIphone = toNewsKitIcon(PhoneIphone);
