// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Archive} from '@emotion-icons/material/Archive';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Archive['displayName'] = "IconFilledArchive";

export const IconFilledArchive = toNewsKitIcon(Archive);
