// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Person} from '@emotion-icons/material/Person';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Person.displayName = 'IconFilledPerson';

export const IconFilledPerson = toNewsKitIcon(Person);
