// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ExitToApp} from '@emotion-icons/material/ExitToApp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ExitToApp.displayName = 'IconFilledExitToApp';

export const IconFilledExitToApp = toNewsKitIcon(ExitToApp);
