// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WbIridescent} from '@emotion-icons/material/WbIridescent';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
WbIridescent['displayName'] = "IconFilledWbIridescent";

export const IconFilledWbIridescent = toNewsKitIcon(WbIridescent);
