// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhotoAlbum} from '@emotion-icons/material/PhotoAlbum';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhotoAlbum.displayName = 'IconFilledPhotoAlbum';

export const IconFilledPhotoAlbum = toNewsKitIcon(PhotoAlbum);
