// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Stairs} from '@emotion-icons/material/Stairs';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Stairs['displayName'] = "IconFilledStairs";

export const IconFilledStairs = toNewsKitIcon(Stairs);
