// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Group} from '@emotion-icons/material/Group';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Group.displayName = 'IconFilledGroup';

export const IconFilledGroup = toNewsKitIcon(Group);
