// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {BorderStyle} from '@emotion-icons/material/BorderStyle';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
BorderStyle['displayName'] = "IconFilledBorderStyle";

export const IconFilledBorderStyle = toNewsKitIcon(BorderStyle);
