// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsEthernet} from '@emotion-icons/material/SettingsEthernet';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SettingsEthernet.displayName = 'IconFilledSettingsEthernet';

export const IconFilledSettingsEthernet = toNewsKitIcon(SettingsEthernet);
