// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TextSnippet} from '@emotion-icons/material/TextSnippet';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
TextSnippet.displayName = 'IconFilledTextSnippet';

export const IconFilledTextSnippet = toNewsKitIcon(TextSnippet);
