// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Announcement} from '@emotion-icons/material/Announcement';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Announcement['displayName'] = "IconFilledAnnouncement";

export const IconFilledAnnouncement = toNewsKitIcon(Announcement);
