// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SettingsInputComposite} from '@emotion-icons/material/SettingsInputComposite';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
SettingsInputComposite['displayName'] = "IconFilledSettingsInputComposite";

export const IconFilledSettingsInputComposite = toNewsKitIcon(SettingsInputComposite);
