// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {InvertColorsOff} from '@emotion-icons/material/InvertColorsOff';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
InvertColorsOff['displayName'] = "IconFilledInvertColorsOff";

export const IconFilledInvertColorsOff = toNewsKitIcon(InvertColorsOff);
