// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ControlPointDuplicate} from '@emotion-icons/material/ControlPointDuplicate';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ControlPointDuplicate['displayName'] = "IconFilledControlPointDuplicate";

export const IconFilledControlPointDuplicate = toNewsKitIcon(ControlPointDuplicate);
