// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Menu} from '@emotion-icons/material/Menu';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Menu.displayName = 'IconFilledMenu';

export const IconFilledMenu = toNewsKitIcon(Menu);
