// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {TagFaces} from '@emotion-icons/material/TagFaces';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
TagFaces['displayName'] = "IconFilledTagFaces";

export const IconFilledTagFaces = toNewsKitIcon(TagFaces);
