// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Camera} from '@emotion-icons/material/Camera';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Camera.displayName = 'IconFilledCamera';

export const IconFilledCamera = toNewsKitIcon(Camera);
