// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {SouthWest} from '@emotion-icons/material/SouthWest';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
SouthWest.displayName = 'IconFilledSouthWest';

export const IconFilledSouthWest = toNewsKitIcon(SouthWest);
