// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Widgets} from '@emotion-icons/material/Widgets';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Widgets['displayName'] = "IconFilledWidgets";

export const IconFilledWidgets = toNewsKitIcon(Widgets);
