// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ArrowDownward} from '@emotion-icons/material/ArrowDownward';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ArrowDownward['displayName'] = "IconFilledArrowDownward";

export const IconFilledArrowDownward = toNewsKitIcon(ArrowDownward);
