// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddIcCall} from '@emotion-icons/material/AddIcCall';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AddIcCall.displayName = 'IconFilledAddIcCall';

export const IconFilledAddIcCall = toNewsKitIcon(AddIcCall);
