// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PestControl} from '@emotion-icons/material/PestControl';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PestControl.displayName = 'IconFilledPestControl';

export const IconFilledPestControl = toNewsKitIcon(PestControl);
