// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Brightness2} from '@emotion-icons/material/Brightness2';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Brightness2.displayName = 'IconFilledBrightness2';

export const IconFilledBrightness2 = toNewsKitIcon(Brightness2);
