// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {DeleteSweep} from '@emotion-icons/material/DeleteSweep';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
DeleteSweep.displayName = 'IconFilledDeleteSweep';

export const IconFilledDeleteSweep = toNewsKitIcon(DeleteSweep);
