// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {WrongLocation} from '@emotion-icons/material/WrongLocation';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
WrongLocation.displayName = 'IconFilledWrongLocation';

export const IconFilledWrongLocation = toNewsKitIcon(WrongLocation);
