// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Article} from '@emotion-icons/material/Article';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Article['displayName'] = "IconFilledArticle";

export const IconFilledArticle = toNewsKitIcon(Article);
