// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Brightness3} from '@emotion-icons/material/Brightness3';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Brightness3.displayName = 'IconFilledBrightness3';

export const IconFilledBrightness3 = toNewsKitIcon(Brightness3);
