// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Dns} from '@emotion-icons/material/Dns';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Dns.displayName = 'IconFilledDns';

export const IconFilledDns = toNewsKitIcon(Dns);
