// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ElectricScooter} from '@emotion-icons/material/ElectricScooter';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ElectricScooter['displayName'] = "IconFilledElectricScooter";

export const IconFilledElectricScooter = toNewsKitIcon(ElectricScooter);
