// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddLocationAlt} from '@emotion-icons/material/AddLocationAlt';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AddLocationAlt.displayName = 'IconFilledAddLocationAlt';

export const IconFilledAddLocationAlt = toNewsKitIcon(AddLocationAlt);
