// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Masks} from '@emotion-icons/material/Masks';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Masks['displayName'] = "IconFilledMasks";

export const IconFilledMasks = toNewsKitIcon(Masks);
