// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {VolumeUp} from '@emotion-icons/material/VolumeUp';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
VolumeUp.displayName = 'IconFilledVolumeUp';

export const IconFilledVolumeUp = toNewsKitIcon(VolumeUp);
