// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CallMissed} from '@emotion-icons/material/CallMissed';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
CallMissed.displayName = 'IconFilledCallMissed';

export const IconFilledCallMissed = toNewsKitIcon(CallMissed);
