// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ChatBubble} from '@emotion-icons/material/ChatBubble';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
ChatBubble['displayName'] = "IconFilledChatBubble";

export const IconFilledChatBubble = toNewsKitIcon(ChatBubble);
