// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AddAPhoto} from '@emotion-icons/material/AddAPhoto';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AddAPhoto.displayName = 'IconFilledAddAPhoto';

export const IconFilledAddAPhoto = toNewsKitIcon(AddAPhoto);
