// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EventSeat} from '@emotion-icons/material/EventSeat';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
EventSeat.displayName = 'IconFilledEventSeat';

export const IconFilledEventSeat = toNewsKitIcon(EventSeat);
