// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Umbrella} from '@emotion-icons/material/Umbrella';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Umbrella.displayName = 'IconFilledUmbrella';

export const IconFilledUmbrella = toNewsKitIcon(Umbrella);
