// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AirplanemodeActive} from '@emotion-icons/material/AirplanemodeActive';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AirplanemodeActive.displayName = 'IconFilledAirplanemodeActive';

export const IconFilledAirplanemodeActive = toNewsKitIcon(AirplanemodeActive);
