// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CommentBank} from '@emotion-icons/material/CommentBank';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
CommentBank.displayName = 'IconFilledCommentBank';

export const IconFilledCommentBank = toNewsKitIcon(CommentBank);
