// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Done} from '@emotion-icons/material/Done';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Done.displayName = 'IconFilledDone';

export const IconFilledDone = toNewsKitIcon(Done);
