// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {EmojiFlags} from '@emotion-icons/material/EmojiFlags';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
EmojiFlags['displayName'] = "IconFilledEmojiFlags";

export const IconFilledEmojiFlags = toNewsKitIcon(EmojiFlags);
