// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PermCameraMic} from '@emotion-icons/material/PermCameraMic';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PermCameraMic.displayName = 'IconFilledPermCameraMic';

export const IconFilledPermCameraMic = toNewsKitIcon(PermCameraMic);
