// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {GpsNotFixed} from '@emotion-icons/material/GpsNotFixed';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
GpsNotFixed['displayName'] = "IconFilledGpsNotFixed";

export const IconFilledGpsNotFixed = toNewsKitIcon(GpsNotFixed);
