// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PhonelinkLock} from '@emotion-icons/material/PhonelinkLock';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PhonelinkLock.displayName = 'IconFilledPhonelinkLock';

export const IconFilledPhonelinkLock = toNewsKitIcon(PhonelinkLock);
