// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {RepeatOne} from '@emotion-icons/material/RepeatOne';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
RepeatOne.displayName = 'IconFilledRepeatOne';

export const IconFilledRepeatOne = toNewsKitIcon(RepeatOne);
