// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {NorthEast} from '@emotion-icons/material/NorthEast';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
NorthEast.displayName = 'IconFilledNorthEast';

export const IconFilledNorthEast = toNewsKitIcon(NorthEast);
