// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PestControlRodent} from '@emotion-icons/material/PestControlRodent';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
PestControlRodent.displayName = 'IconFilledPestControlRodent';

export const IconFilledPestControlRodent = toNewsKitIcon(PestControlRodent);
