// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {ViewColumn} from '@emotion-icons/material/ViewColumn';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
ViewColumn.displayName = 'IconFilledViewColumn';

export const IconFilledViewColumn = toNewsKitIcon(ViewColumn);
