// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {CallToAction} from '@emotion-icons/material/CallToAction';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
CallToAction['displayName'] = "IconFilledCallToAction";

export const IconFilledCallToAction = toNewsKitIcon(CallToAction);
