// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Crop169} from '@emotion-icons/material/Crop169';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Crop169['displayName'] = "IconFilledCrop169";

export const IconFilledCrop169 = toNewsKitIcon(Crop169);
