// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {FormatShapes} from '@emotion-icons/material/FormatShapes';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
FormatShapes.displayName = 'IconFilledFormatShapes';

export const IconFilledFormatShapes = toNewsKitIcon(FormatShapes);
