// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {PersonPin} from '@emotion-icons/material/PersonPin';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
PersonPin['displayName'] = "IconFilledPersonPin";

export const IconFilledPersonPin = toNewsKitIcon(PersonPin);
