// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Keyboard} from '@emotion-icons/material/Keyboard';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Keyboard['displayName'] = "IconFilledKeyboard";

export const IconFilledKeyboard = toNewsKitIcon(Keyboard);
