// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Timer} from '@emotion-icons/material/Timer';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Timer.displayName = 'IconFilledTimer';

export const IconFilledTimer = toNewsKitIcon(Timer);
