// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Phonelink} from '@emotion-icons/material/Phonelink';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Phonelink.displayName = 'IconFilledPhonelink';

export const IconFilledPhonelink = toNewsKitIcon(Phonelink);
