// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Gif} from '@emotion-icons/material/Gif';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
Gif['displayName'] = "IconFilledGif";

export const IconFilledGif = toNewsKitIcon(Gif);
