// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {AirlineSeatReclineNormal} from '@emotion-icons/material/AirlineSeatReclineNormal';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
AirlineSeatReclineNormal.displayName = 'IconFilledAirlineSeatReclineNormal';

export const IconFilledAirlineSeatReclineNormal = toNewsKitIcon(
  AirlineSeatReclineNormal,
);
