// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Speed} from '@emotion-icons/material/Speed';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Speed.displayName = 'IconFilledSpeed';

export const IconFilledSpeed = toNewsKitIcon(Speed);
