// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {HourglassDisabled} from '@emotion-icons/material/HourglassDisabled';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overridden
HourglassDisabled['displayName'] = "IconFilledHourglassDisabled";

export const IconFilledHourglassDisabled = toNewsKitIcon(HourglassDisabled);
