// This file is automatically generated do not modify it. See generate-icons.js for documentation.
import {Luggage} from '@emotion-icons/material/Luggage';
import {toNewsKitIcon} from '../../to-newskit-icon';

// The updated display name will be used to return the right icon in
// "to-newskit-icon.tsx", if it gets overritten
Luggage.displayName = 'IconFilledLuggage';

export const IconFilledLuggage = toNewsKitIcon(Luggage);
