"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Accordion = void 0;
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importStar(require("react"));
var react_transition_group_1 = require("react-transition-group");
var compose_react_refs_1 = tslib_1.__importDefault(require("@seznam/compose-react-refs"));
var with_own_theme_1 = require("../utils/with-own-theme");
var styled_1 = require("./styled");
var defaults_1 = tslib_1.__importDefault(require("./defaults"));
var style_presets_1 = tslib_1.__importDefault(require("./style-presets"));
var hooks_1 = require("../utils/hooks");
var icons_1 = require("../icons");
var overrides_1 = require("../utils/overrides");
var text_block_1 = require("../text-block");
var compose_event_handlers_1 = require("../utils/compose-event-handlers");
var get_transition_class_name_1 = require("../utils/get-transition-class-name");
var utils_1 = require("../utils");
var theme_1 = require("../theme");
var utils_2 = require("./utils");
var instrumentation_1 = require("../instrumentation");
// Based on https://www.w3schools.com/howto/howto_js_accordion.asp
var MaxHeightTransitionPanel = react_1.default.forwardRef(function (_a, transitionRef) {
    var expanded = _a.expanded, children = _a.children, overrides = _a.overrides, className = _a.className;
    var ref = (0, react_1.useRef)(null);
    var width = (0, hooks_1.useResizeObserver)(ref)[0];
    (0, react_1.useEffect)(function () {
        if (expanded) {
            ref.current.style.maxHeight = "".concat((0, utils_2.getRefScrollHeight)(ref.current), "px");
        }
        else {
            ref.current.style.maxHeight = '0px';
        }
    }, [expanded, width]);
    return (react_1.default.createElement(styled_1.StyledPanelTransitionContainer, { "data-testid": "panel-transition-container", ref: (0, compose_react_refs_1.default)(transitionRef, ref), expanded: expanded, overrides: overrides, className: className }, children));
});
var DefaultIcon = function (_a) {
    var expanded = _a.expanded, overrides = _a.overrides;
    return expanded ? (react_1.default.createElement(icons_1.IconFilledExpandLess, { overrides: tslib_1.__assign({ size: 'iconSize020' }, overrides) })) : (react_1.default.createElement(icons_1.IconFilledExpandMore, { overrides: tslib_1.__assign({ size: 'iconSize020' }, overrides) }));
};
var ThemelessAccordion = react_1.default.forwardRef(function (_a, ref) {
    var _b;
    var _c = _a.headerAs, headerAs = _c === void 0 ? 'h3' : _c, header = _a.header, label = _a.label, expanded = _a.expanded, _d = _a.disabled, disabled = _d === void 0 ? false : _d, children = _a.children, ariaControls = _a.ariaControls, id = _a.id, overrides = _a.overrides, onClickProp = _a.onClick, _e = _a.onChange, onChangeProp = _e === void 0 ? function () { return null; } : _e, _f = _a.eventContext, eventContext = _f === void 0 ? {} : _f, _g = _a.eventOriginator, eventOriginator = _g === void 0 ? 'accordion' : _g, props = tslib_1.__rest(_a, ["headerAs", "header", "label", "expanded", "disabled", "children", "ariaControls", "id", "overrides", "onClick", "onChange", "eventContext", "eventOriginator"]);
    var autoGeneratedID = (0, hooks_1.useReactKeys)(1)[0];
    var ariaControlsId = ariaControls || "".concat(autoGeneratedID, "-content");
    var ariaLabelledById = id || "".concat(autoGeneratedID, "-control");
    var cssTransitionNodeRef = react_1.default.useRef(null);
    var _h = (0, overrides_1.getComponentOverrides)((_b = overrides === null || overrides === void 0 ? void 0 : overrides.header) === null || _b === void 0 ? void 0 : _b.indicatorIcon, DefaultIcon, {
        expanded: expanded,
    }), IndicatorIcon = _h[0], indicatorIconProps = _h[1];
    var fireEvent = (0, instrumentation_1.useInstrumentation)().fireEvent;
    var onClick = (0, compose_event_handlers_1.composeEventHandlers)([
        onClickProp,
        function () { return onChangeProp(!expanded); },
        function () {
            return fireEvent({
                originator: eventOriginator,
                trigger: instrumentation_1.EventTrigger.Click,
                context: tslib_1.__assign({}, eventContext),
            });
        },
    ]);
    var theme = (0, theme_1.useTheme)();
    return (react_1.default.createElement(styled_1.StyledAccordionWrapper, { ref: ref, overrides: overrides },
        react_1.default.createElement(text_block_1.TextBlock, { as: headerAs },
            react_1.default.createElement(styled_1.StyledAccordionButton, tslib_1.__assign({ overrides: overrides, disabled: disabled, "aria-expanded": expanded, "aria-controls": ariaControlsId, id: ariaLabelledById, "data-testid": "accordion-control", onClick: onClick }, props),
                react_1.default.createElement(styled_1.StyledHeader, null, header),
                label && react_1.default.createElement(styled_1.StyledLabel, { overrides: overrides }, label),
                react_1.default.createElement(styled_1.StyledIconWrapper, null,
                    react_1.default.createElement(IndicatorIcon, tslib_1.__assign({}, indicatorIconProps))))),
        react_1.default.createElement(react_transition_group_1.CSSTransition, { nodeRef: cssTransitionNodeRef, in: expanded, timeout: (0, utils_1.getTransitionDuration)("accordion.panel", 'panel')({ theme: theme, overrides: overrides }), classNames: "nk-accordion" }, function (state) { return (react_1.default.createElement(MaxHeightTransitionPanel, { className: (0, get_transition_class_name_1.getTransitionClassName)('nk-accordion', state), expanded: expanded, overrides: overrides, ref: cssTransitionNodeRef },
            react_1.default.createElement(styled_1.StyledPanel, { "aria-labelledby": ariaLabelledById, id: ariaControlsId, "data-testid": "accordion-content", role: "region", expanded: expanded, overrides: overrides }, children))); })));
});
exports.Accordion = (0, with_own_theme_1.withOwnTheme)(ThemelessAccordion)({
    defaults: defaults_1.default,
    stylePresets: style_presets_1.default,
});
exports.Accordion.displayName = 'Accordion';
//# sourceMappingURL=accordion.js.map