"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.outlines = exports.sizing = exports.shadows = exports.overlays = exports.fonts = exports.colors = exports.breakpoints = exports.borders = exports.motions = void 0;
var motions_1 = require("./motions");
Object.defineProperty(exports, "motions", { enumerable: true, get: function () { return motions_1.motions; } });
var borders_1 = require("./borders");
Object.defineProperty(exports, "borders", { enumerable: true, get: function () { return borders_1.borders; } });
var breakpoints_1 = require("./breakpoints");
Object.defineProperty(exports, "breakpoints", { enumerable: true, get: function () { return breakpoints_1.breakpoints; } });
var colors_1 = require("./colors");
Object.defineProperty(exports, "colors", { enumerable: true, get: function () { return colors_1.colors; } });
var fonts_1 = require("./fonts");
Object.defineProperty(exports, "fonts", { enumerable: true, get: function () { return fonts_1.fonts; } });
var overlays_1 = require("./overlays");
Object.defineProperty(exports, "overlays", { enumerable: true, get: function () { return overlays_1.overlays; } });
var shadows_1 = require("./shadows");
Object.defineProperty(exports, "shadows", { enumerable: true, get: function () { return shadows_1.shadows; } });
var sizing_1 = require("./sizing");
Object.defineProperty(exports, "sizing", { enumerable: true, get: function () { return sizing_1.sizing; } });
var outlines_1 = require("./outlines");
Object.defineProperty(exports, "outlines", { enumerable: true, get: function () { return outlines_1.outlines; } });
//# sourceMappingURL=index.js.map