//@ts-nocheck
// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export function gql(strings: TemplateStringsArray, ...args: string[]): string {
  let str = ''
  strings.forEach((string, i) => {
    str += string + (args[i] || '')
  })
  return str
}
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  title?: Maybe<Scalars['String']>;
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  id: Scalars['ID'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  component: Component;
  componentConnection: ComponentConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryComponentArgs = {
  relativePath?: InputMaybe<Scalars['String']>;
};


export type QueryComponentConnectionArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label?: Maybe<Scalars['String']>;
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
};

export type DocumentNode = Component;

export type ComponentPageIntro = {
  __typename?: 'ComponentPageIntro';
  type?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  coverImage?: Maybe<Scalars['String']>;
  introduction?: Maybe<Scalars['String']>;
};

export type Component = Node & Document & {
  __typename?: 'Component';
  pageIntro?: Maybe<ComponentPageIntro>;
  id: Scalars['ID'];
  _sys: SystemInfo;
  _values: Scalars['JSON'];
};

export type ComponentConnectionEdges = {
  __typename?: 'ComponentConnectionEdges';
  cursor: Scalars['String'];
  node?: Maybe<Component>;
};

export type ComponentConnection = Connection & {
  __typename?: 'ComponentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float'];
  edges?: Maybe<Array<Maybe<ComponentConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  updateComponent: Component;
  createComponent: Component;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: InputMaybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']>;
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateComponentArgs = {
  relativePath: Scalars['String'];
  params: ComponentMutation;
};


export type MutationCreateComponentArgs = {
  relativePath: Scalars['String'];
  params: ComponentMutation;
};

export type DocumentMutation = {
  component?: InputMaybe<ComponentMutation>;
};

export type ComponentPageIntroMutation = {
  type?: InputMaybe<Scalars['String']>;
  name?: InputMaybe<Scalars['String']>;
  coverImage?: InputMaybe<Scalars['String']>;
  introduction?: InputMaybe<Scalars['String']>;
};

export type ComponentMutation = {
  pageIntro?: InputMaybe<ComponentPageIntroMutation>;
};

export type ComponentPartsFragment = { __typename?: 'Component', pageIntro?: { __typename: 'ComponentPageIntro', type?: string | null, name?: string | null, coverImage?: string | null, introduction?: string | null } | null };

export type ComponentQueryVariables = Exact<{
  relativePath: Scalars['String'];
}>;


export type ComponentQuery = { __typename?: 'Query', component: { __typename?: 'Component', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pageIntro?: { __typename: 'ComponentPageIntro', type?: string | null, name?: string | null, coverImage?: string | null, introduction?: string | null } | null } };

export type ComponentConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']>;
  after?: InputMaybe<Scalars['String']>;
  first?: InputMaybe<Scalars['Float']>;
  last?: InputMaybe<Scalars['Float']>;
  sort?: InputMaybe<Scalars['String']>;
}>;


export type ComponentConnectionQuery = { __typename?: 'Query', componentConnection: { __typename?: 'ComponentConnection', totalCount: number, edges?: Array<{ __typename?: 'ComponentConnectionEdges', node?: { __typename?: 'Component', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, pageIntro?: { __typename: 'ComponentPageIntro', type?: string | null, name?: string | null, coverImage?: string | null, introduction?: string | null } | null } | null } | null> | null } };

export const ComponentPartsFragmentDoc = gql`
    fragment ComponentParts on Component {
  pageIntro {
    __typename
    type
    name
    coverImage
    introduction
  }
}
    `;
export const ComponentDocument = gql`
    query component($relativePath: String!) {
  component(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ComponentParts
  }
}
    ${ComponentPartsFragmentDoc}`;
export const ComponentConnectionDocument = gql`
    query componentConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String) {
  componentConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
  ) {
    totalCount
    edges {
      node {
        ... on Document {
          _sys {
            filename
            basename
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ComponentParts
      }
    }
  }
}
    ${ComponentPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      component(variables: ComponentQueryVariables, options?: C): Promise<{data: ComponentQuery, variables: ComponentQueryVariables, query: string}> {
        return requester<{data: ComponentQuery, variables: ComponentQueryVariables, query: string}, ComponentQueryVariables>(ComponentDocument, variables, options);
      },
    componentConnection(variables?: ComponentConnectionQueryVariables, options?: C): Promise<{data: ComponentConnectionQuery, variables: ComponentConnectionQueryVariables, query: string}> {
        return requester<{data: ComponentConnectionQuery, variables: ComponentConnectionQueryVariables, query: string}, ComponentConnectionQueryVariables>(ComponentConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (client: TinaClient) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: any,
    client
  ) => Promise<any> = async (doc, vars, _options) => {
    let data = {};
    try {
      data = await client.request({
        query: doc,
        variables: vars,
      });
    } catch (e) {
      // swallow errors related to document creation
      console.warn("Warning: There was an error when fetching data");
      console.warn(e);
    }

    return { data: data?.data, query: doc, variables: vars || {} };
  };

  return requester;
};

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(createClient({ url: "http://localhost:4001/graphql" }))
  );

export const queries = (client: TinaClient) => {
  const requester = generateRequester(client);
  return getSdk(requester);
};

