import { __assign, __rest } from "tslib";
import React, { useEffect, useRef } from 'react';
import { CSSTransition } from 'react-transition-group';
import composeRefs from '@seznam/compose-react-refs';
import { withOwnTheme } from '../utils/with-own-theme';
import { StyledAccordionButton, StyledPanel, StyledLabel, StyledIconWrapper, StyledHeader, StyledPanelTransitionContainer, StyledAccordionWrapper, } from './styled';
import defaults from './defaults';
import stylePresets from './style-presets';
import { useReactKeys, useResizeObserver } from '../utils/hooks';
import { IconFilledExpandLess, IconFilledExpandMore } from '../icons';
import { getComponentOverrides } from '../utils/overrides';
import { TextBlock } from '../text-block';
import { composeEventHandlers } from '../utils/compose-event-handlers';
import { getTransitionClassName } from '../utils/get-transition-class-name';
import { getTransitionDuration } from '../utils';
import { useTheme } from '../theme';
import { getRefScrollHeight } from './utils';
import { EventTrigger, useInstrumentation } from '../instrumentation';
// Based on https://www.w3schools.com/howto/howto_js_accordion.asp
var MaxHeightTransitionPanel = React.forwardRef(function (_a, transitionRef) {
    var expanded = _a.expanded, children = _a.children, overrides = _a.overrides, className = _a.className;
    var ref = useRef(null);
    var width = useResizeObserver(ref)[0];
    useEffect(function () {
        if (expanded) {
            ref.current.style.maxHeight = "".concat(getRefScrollHeight(ref.current), "px");
        }
        else {
            ref.current.style.maxHeight = '0px';
        }
    }, [expanded, width]);
    return (React.createElement(StyledPanelTransitionContainer, { "data-testid": "panel-transition-container", ref: composeRefs(transitionRef, ref), expanded: expanded, overrides: overrides, className: className }, children));
});
var DefaultIcon = function (_a) {
    var expanded = _a.expanded, overrides = _a.overrides;
    return expanded ? (React.createElement(IconFilledExpandLess, { overrides: __assign({ size: 'iconSize020' }, overrides) })) : (React.createElement(IconFilledExpandMore, { overrides: __assign({ size: 'iconSize020' }, overrides) }));
};
var ThemelessAccordion = React.forwardRef(function (_a, ref) {
    var _b;
    var _c = _a.headerAs, headerAs = _c === void 0 ? 'h3' : _c, header = _a.header, label = _a.label, expanded = _a.expanded, _d = _a.disabled, disabled = _d === void 0 ? false : _d, children = _a.children, ariaControls = _a.ariaControls, id = _a.id, overrides = _a.overrides, onClickProp = _a.onClick, _e = _a.onChange, onChangeProp = _e === void 0 ? function () { return null; } : _e, _f = _a.eventContext, eventContext = _f === void 0 ? {} : _f, _g = _a.eventOriginator, eventOriginator = _g === void 0 ? 'accordion' : _g, props = __rest(_a, ["headerAs", "header", "label", "expanded", "disabled", "children", "ariaControls", "id", "overrides", "onClick", "onChange", "eventContext", "eventOriginator"]);
    var autoGeneratedID = useReactKeys(1)[0];
    var ariaControlsId = ariaControls || "".concat(autoGeneratedID, "-content");
    var ariaLabelledById = id || "".concat(autoGeneratedID, "-control");
    var cssTransitionNodeRef = React.useRef(null);
    var _h = getComponentOverrides((_b = overrides === null || overrides === void 0 ? void 0 : overrides.header) === null || _b === void 0 ? void 0 : _b.indicatorIcon, DefaultIcon, {
        expanded: expanded,
    }), IndicatorIcon = _h[0], indicatorIconProps = _h[1];
    var fireEvent = useInstrumentation().fireEvent;
    var onClick = composeEventHandlers([
        onClickProp,
        function () { return onChangeProp(!expanded); },
        function () {
            return fireEvent({
                originator: eventOriginator,
                trigger: EventTrigger.Click,
                context: __assign({}, eventContext),
            });
        },
    ]);
    var theme = useTheme();
    return (React.createElement(StyledAccordionWrapper, { ref: ref, overrides: overrides },
        React.createElement(TextBlock, { as: headerAs },
            React.createElement(StyledAccordionButton, __assign({ overrides: overrides, disabled: disabled, "aria-expanded": expanded, "aria-controls": ariaControlsId, id: ariaLabelledById, "data-testid": "accordion-control", onClick: onClick }, props),
                React.createElement(StyledHeader, null, header),
                label && React.createElement(StyledLabel, { overrides: overrides }, label),
                React.createElement(StyledIconWrapper, null,
                    React.createElement(IndicatorIcon, __assign({}, indicatorIconProps))))),
        React.createElement(CSSTransition, { nodeRef: cssTransitionNodeRef, in: expanded, timeout: getTransitionDuration("accordion.panel", 'panel')({ theme: theme, overrides: overrides }), classNames: "nk-accordion" }, function (state) { return (React.createElement(MaxHeightTransitionPanel, { className: getTransitionClassName('nk-accordion', state), expanded: expanded, overrides: overrides, ref: cssTransitionNodeRef },
            React.createElement(StyledPanel, { "aria-labelledby": ariaLabelledById, id: ariaControlsId, "data-testid": "accordion-content", role: "region", expanded: expanded, overrides: overrides }, children))); })));
});
export var Accordion = withOwnTheme(ThemelessAccordion)({
    defaults: defaults,
    stylePresets: stylePresets,
});
Accordion.displayName = 'Accordion';
//# sourceMappingURL=accordion.js.map