export default {
  flag: {
    small: {
      typographyPreset: 'utilityLabel010',
      stylePreset: 'flagSolidPrimary',
      paddingInlineStart: 'space020',
      paddingInlineEnd: 'space020',
      paddingBlockStart: 'space010',
      paddingBlockEnd: 'space010',
      minHeight: 'sizing050',
      iconSize: 'iconSize010',
      spaceInline: 'space010',
    },
    medium: {
      typographyPreset: 'utilityLabel020',
      stylePreset: 'flagSolidPrimary',
      paddingInlineStart: 'space030',
      paddingInlineEnd: 'space030',
      paddingBlockStart: 'space020',
      paddingBlockEnd: 'space020',
      minHeight: 'sizing060',
      iconSize: 'iconSize010',
      spaceInline: 'space010',
    },
    large: {
      typographyPreset: 'utilityLabel030',
      stylePreset: 'flagSolidPrimary',
      paddingInlineStart: 'space030',
      paddingInlineEnd: 'space030',
      paddingBlockStart: 'space020',
      paddingBlockEnd: 'space020',
      minHeight: 'sizing070',
      iconSize: 'iconSize010',
      spaceInline: 'space010',
    },
  },
};
