export default {
  textArea: {
    small: {
      stylePreset: 'inputField',
      minHeight: 'sizing070',
      height: 'sizing100',
      width: '100%',
      typographyPreset: 'utilityBody020',
      paddingBlockStart: 'space020',
      paddingBlockEnd: 'space020',
      paddingInlineStart: 'space020',
      paddingInlineEnd: 'space020',
      marginBlockEnd: 'space020',
    },
    medium: {
      stylePreset: 'inputField',
      minHeight: 'sizing080',
      height: 'sizing110',
      width: '100%',
      typographyPreset: 'utilityBody020',
      paddingBlockStart: 'space030',
      paddingBlockEnd: 'space030',
      paddingInlineStart: 'space030',
      paddingInlineEnd: 'space030',
      marginBlockEnd: 'space020',
    },
    large: {
      stylePreset: 'inputField',
      minHeight: 'sizing090',
      height: 'sizing110',
      width: '100%',
      typographyPreset: 'utilityBody030',
      paddingBlockStart: 'space040',
      paddingBlockEnd: 'space040',
      paddingInlineStart: 'space040',
      paddingInlineEnd: 'space040',
      marginBlockEnd: 'space020',
    },
  },
};
