import { __assign, __rest } from "tslib";
import React, { useContext, useEffect, useState } from 'react';
import composeRefs from '@seznam/compose-react-refs';
import { Label } from '../label';
import { TextField } from '../text-field/text-field';
import { AssistiveText } from '../assistive-text';
import { getStatusIcon } from './utils';
import { composeEventHandlers } from '../utils/compose-event-handlers';
import { Checkbox } from '../checkbox';
import { useReactKeys } from '../utils/hooks';
import { getToken } from '../utils/get-token';
import { useTheme } from '../theme';
import { FormEntry } from './form-entry';
import { Block } from '../block';
import { Select } from '../select';
import { FormInputContext } from './context';
import { withOwnTheme } from '../utils/with-own-theme';
import textFieldDefaults from '../text-field/defaults';
import assistiveTextDefaults from '../assistive-text/defaults';
import { RadioButton } from '../radio-button';
import { TextArea } from '../text-area';
import { CharacterCount } from '../character-count';
var useFormFieldContext = function () { return useContext(FormInputContext); };
var setState = function (state, isRequired, hasContent) {
    var isOptionalAndEmpty = !isRequired && !hasContent && state === 'valid';
    if (isOptionalAndEmpty)
        return undefined;
    return state;
};
var ThemelessFormInput = function (_a) {
    var name = _a.name, rules = _a.rules, stateProp = _a.state, size = _a.size, children = _a.children, id = _a.id;
    var defaultSize = 'medium';
    var autoGeneratedId = useReactKeys(1)[0];
    var currentID = id || autoGeneratedId;
    var _b = useState(), assistiveTextId = _b[0], setAssistiveTextId = _b[1];
    var theme = useTheme();
    var validationIconSize = getToken({ theme: theme, overrides: {} }, "textField.".concat(size || defaultSize, ".endEnhancer"), 'endEnhancer', 'iconSize');
    var passedInputFieldContext = useFormFieldContext();
    return (React.createElement(FormEntry, { name: name, rules: rules }, function (_a) {
        var ref = _a.ref, stateContext = _a.state, onChange = _a.onChange, onBlur = _a.onBlur, error = _a.error, refObject = _a.refObject, hasContent = _a.hasContent;
        var isRequired = rules && rules.required !== undefined;
        var state = stateProp || setState(stateContext, isRequired, hasContent);
        var labelId = "".concat(currentID, "-label");
        var statusIcon = getStatusIcon({ state: state, iconSize: validationIconSize });
        var inputFieldContext = {
            name: name,
            size: size || passedInputFieldContext.size || defaultSize,
            onChange: onChange,
            onBlur: onBlur,
            state: state,
            error: error,
            ref: ref,
            id: currentID,
            assistiveTextId: assistiveTextId,
            setAssistiveTextId: setAssistiveTextId,
            labelId: labelId,
            statusIcon: statusIcon,
            isRequired: isRequired,
            refObject: refObject,
            rules: rules,
        };
        return (React.createElement(FormInputContext.Provider, { value: inputFieldContext }, children));
    }));
};
export var FormInput = withOwnTheme(ThemelessFormInput)({
    defaults: __assign(__assign({}, textFieldDefaults), assistiveTextDefaults),
});
export var FormInputTextField = React.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, endEnhancer = _a.endEnhancer, props = __rest(_a, ["children", "onChange", "onBlur", "endEnhancer"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, statusIcon = _b.statusIcon, isRequired = _b.isRequired;
    function getEndEnhancer() {
        if (!statusIcon) {
            return endEnhancer;
        }
        if (endEnhancer) {
            return (React.createElement(React.Fragment, null,
                statusIcon,
                " ",
                React.createElement(Block, { spaceInline: "space020" }),
                " ",
                endEnhancer,
                ' '));
        }
        return statusIcon;
    }
    return (React.createElement(TextField, __assign({ "aria-required": isRequired || undefined, "aria-invalid": state === 'invalid' ? 'true' : 'false', name: name, state: state, size: size, onChange: composeEventHandlers([onChange, onChangeContext]), onBlur: composeEventHandlers([onBlur, onBlurContext]), ref: composeRefs(ref, inputRef), endEnhancer: getEndEnhancer(), id: id, "aria-describedby": assistiveTextId }, props)));
});
export var FormInputLabel = function (_a) {
    var children = _a.children, props = __rest(_a, ["children"]);
    var _b = useFormFieldContext(), size = _b.size, state = _b.state, id = _b.id, labelId = _b.labelId;
    return (React.createElement(Label, __assign({ id: labelId, size: size, state: state, htmlFor: id }, props), children));
};
export var FormInputSelect = React.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = __rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, labelId = _b.labelId, statusIcon = _b.statusIcon, isRequired = _b.isRequired;
    return (React.createElement(Select, __assign({ name: name, state: state, size: size, "aria-labelledby": "".concat(labelId, " ").concat(id), validationIcon: statusIcon, onChange: composeEventHandlers([onChange, onChangeContext]), onBlur: composeEventHandlers([onBlur, onBlurContext]), ref: composeRefs(ref, inputRef), id: id, labelId: labelId, "aria-describedby": assistiveTextId, required: isRequired || undefined }, props), children));
});
export var FormInputAssistiveText = function (_a) {
    var children = _a.children, _b = _a.validationIcon, validationIcon = _b === void 0 ? false : _b, overrides = _a.overrides, props = __rest(_a, ["children", "validationIcon", "overrides"]);
    var _c = useFormFieldContext(), size = _c.size, state = _c.state, error = _c.error, assistiveTextId = _c.assistiveTextId, setAssistiveTextId = _c.setAssistiveTextId, id = _c.id;
    useEffect(function () {
        if (setAssistiveTextId) {
            setAssistiveTextId(state === 'invalid' ? "".concat(id, "-error-text") : "".concat(id, "-assistive-text"));
        }
    }, [state, id, setAssistiveTextId]);
    var theme = useTheme();
    var validationIconSize = getToken({ theme: theme, overrides: {} }, "assistiveText.".concat(size, ".startEnhancer"), 'startEnhancer', 'iconSize');
    var statusIcon = getStatusIcon({ state: state, iconSize: validationIconSize });
    return (React.createElement(AssistiveText, __assign({ size: size, state: state, id: assistiveTextId, startEnhancer: validationIcon ? statusIcon : undefined, overrides: overrides }, props), error || children));
};
export var FormInputCheckbox = React.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = __rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (React.createElement(Checkbox, __assign({ name: name, state: state, size: size, onChange: composeEventHandlers([onChange, onChangeContext]), onBlur: composeEventHandlers([onBlur, onBlurContext]), ref: composeRefs(ref, inputRef), id: id, "aria-describedby": assistiveTextId, "aria-required": isRequired || undefined }, props)));
});
export var FormInputRadioButton = React.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = __rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (React.createElement(RadioButton, __assign({ name: name, state: state, size: size, onChange: composeEventHandlers([onChange, onChangeContext]), onBlur: composeEventHandlers([onBlur, onBlurContext]), ref: composeRefs(ref, inputRef), id: id, "aria-describedby": assistiveTextId, "aria-required": isRequired || undefined }, props)));
});
export var FormInputTextArea = React.forwardRef(function (_a, elementRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = __rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (React.createElement(TextArea, __assign({ "aria-required": isRequired || undefined, "aria-invalid": state === 'invalid' ? 'true' : 'false', name: name, state: state, size: size, onChange: composeEventHandlers([onChange, onChangeContext]), onBlur: composeEventHandlers([onBlur, onBlurContext]), ref: composeRefs(elementRef, ref), id: id, "aria-describedby": assistiveTextId }, props)));
});
function isValidationValueMessage(valueOrObj) {
    return valueOrObj.value !== undefined;
}
function asNumber(value) {
    if (typeof value === 'string') {
        return parseInt(value, 10);
    }
    return value;
}
var getValueFromRule = function (value) {
    if (!!value && isValidationValueMessage(value)) {
        return asNumber(value.value);
    }
    if (value) {
        return asNumber(value);
    }
    return undefined;
};
export var FormInputCharacterCount = function (props) {
    var _a = useFormFieldContext(), refObject = _a.refObject, state = _a.state, size = _a.size, rules = _a.rules;
    var _b = (rules || {}), minLength = _b.minLength, maxLength = _b.maxLength;
    return (React.createElement(CharacterCount, __assign({ state: state, size: size, inputRef: refObject, minLength: getValueFromRule(minLength), maxLength: getValueFromRule(maxLength) }, props)));
};
//# sourceMappingURL=form-input.js.map