export default {
  button: {
    small: {
      typographyPreset: 'utilityButton010',
      stylePreset: 'buttonSolidPrimary',
      paddingInlineStart: 'space030',
      paddingInlineEnd: 'space030',
      paddingBlockStart: 'space020',
      paddingBlockEnd: 'space020',
      minWidth: 'sizing090',
      minHeight: 'sizing060',
      iconSize: 'iconSize010',
      spaceInline: 'space020',
      transitionPreset: 'backgroundColorChange',
      loadingIndicator: {
        stylePreset: 'indeterminateProgressIndicatorPrimary',
      },
    },
    medium: {
      typographyPreset: 'utilityButton020',
      stylePreset: 'buttonSolidPrimary',
      paddingInlineStart: 'space040',
      paddingInlineEnd: 'space040',
      paddingBlockStart: 'space030',
      paddingBlockEnd: 'space030',
      minWidth: 'sizing100',
      minHeight: 'sizing080',
      iconSize: 'iconSize020',
      spaceInline: 'space020',
      transitionPreset: 'backgroundColorChange',
      loadingIndicator: {
        stylePreset: 'indeterminateProgressIndicatorPrimary',
      },
    },
    large: {
      typographyPreset: 'utilityButton030',
      stylePreset: 'buttonSolidPrimary',
      paddingInlineStart: 'space050',
      paddingInlineEnd: 'space050',
      paddingBlockStart: 'space040',
      paddingBlockEnd: 'space040',
      minWidth: 'sizing110',
      minHeight: 'sizing090',
      iconSize: 'iconSize030',
      spaceInline: 'space020',
      transitionPreset: 'backgroundColorChange',
      loadingIndicator: {
        stylePreset: 'indeterminateProgressIndicatorPrimary',
      },
    },
  },
};
