import {createTheme} from '../creator';
import {colorPalettes} from '../newskit-light/colors';
import {overlayPrimitives} from '../newskit-light/overlay';

const darkThemeModifiers = {
  inkBase: colorPalettes.neutral020,
  inkContrast: colorPalettes.neutral010,
  inkSubtle: colorPalettes.neutral040,
  inkNonEssential: colorPalettes.neutral070,
  inkInverse: colorPalettes.black,
  inkHeadingLink: colorPalettes.neutral020,
  inkHeadingLinkHover: colorPalettes.inkLink,
  inkHeadingLinkActive: colorPalettes.inkLink,
  inkHeadingLinkVisited: colorPalettes.neutral020,
  inkNegative: colorPalettes.red050,
  inkPositive: colorPalettes.green050,
  inkNotice: colorPalettes.amber040,
  inkInformative: colorPalettes.purple030,
  inkBrand010: colorPalettes.blue050,
  inkLink: colorPalettes.inkLink,
  inkLinkHover: colorPalettes.inkLink,
  inkLinkActive: colorPalettes.inkLink,
  inkLinkVisited: colorPalettes.inkLinkVisited,
  semanticNegative010: colorPalettes.red090,
  semanticNegative020: colorPalettes.red100,
  semanticNegative030: colorPalettes.red060,
  semanticNegative040: colorPalettes.red070,
  semanticNegative050: colorPalettes.red070,
  semanticPositive010: colorPalettes.green090,
  semanticPositive020: colorPalettes.green100,
  semanticPositive030: colorPalettes.green060,
  semanticPositive040: colorPalettes.green070,
  semanticPositive050: colorPalettes.green080,
  semanticInformative010: colorPalettes.purple040,
  semanticNotice010: colorPalettes.amber060,
  interfaceBackground: colorPalettes.neutral100,
  interface010: colorPalettes.neutral100,
  interface020: colorPalettes.neutral090,
  interface030: colorPalettes.neutral080,
  interface040: colorPalettes.neutral070,
  interface050: colorPalettes.neutral060,
  interface060: colorPalettes.neutral010,
  interfaceBrand010: colorPalettes.blue060,
  interfaceBrand020: colorPalettes.blue020,
  overlayDark010: overlayPrimitives.overlayLight010,
  overlayDark020: overlayPrimitives.overlayLight020,
  overlayDark030: overlayPrimitives.overlayLight030,
  overlayDark040: overlayPrimitives.overlayLight040,
  overlayLight010: overlayPrimitives.overlayDark010,
  overlayLight020: overlayPrimitives.overlayDark020,
  overlayLight030: overlayPrimitives.overlayDark030,
  overlayLight040: overlayPrimitives.overlayDark040,
  gradientLight010: overlayPrimitives.gradientLight010,
  gradientDark010: overlayPrimitives.gradientDark010,
  interactive010: colorPalettes.blue090,
  interactive020: colorPalettes.blue100,
  interactive030: colorPalettes.blue060,
  interactive040: colorPalettes.blue070,
  interactive050: colorPalettes.blue080,
  interactive110: colorPalettes.neutral080,
  interactive120: colorPalettes.neutral090,
  interactive130: colorPalettes.neutral070,
  interactive140: colorPalettes.neutral080,
  interactive150: colorPalettes.neutral090,
  disabled: colorPalettes.neutral090,
  skeleton010: colorPalettes.neutral090,
  skeleton020: colorPalettes.neutral080,
  inverse: colorPalettes.black,
  transparent: colorPalettes.transparent,
};
export const newskitDarkTheme = createTheme('newskit-dark', {
  colorOverrides: darkThemeModifiers,
});
