"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FormInputCharacterCount = exports.FormInputTextArea = exports.FormInputRadioButton = exports.FormInputCheckbox = exports.FormInputAssistiveText = exports.FormInputSelect = exports.FormInputLabel = exports.FormInputTextField = exports.FormInput = void 0;
var tslib_1 = require("tslib");
var react_1 = tslib_1.__importStar(require("react"));
var compose_react_refs_1 = tslib_1.__importDefault(require("@seznam/compose-react-refs"));
var label_1 = require("../label");
var text_field_1 = require("../text-field/text-field");
var assistive_text_1 = require("../assistive-text");
var utils_1 = require("./utils");
var compose_event_handlers_1 = require("../utils/compose-event-handlers");
var checkbox_1 = require("../checkbox");
var hooks_1 = require("../utils/hooks");
var get_token_1 = require("../utils/get-token");
var theme_1 = require("../theme");
var form_entry_1 = require("./form-entry");
var block_1 = require("../block");
var select_1 = require("../select");
var context_1 = require("./context");
var with_own_theme_1 = require("../utils/with-own-theme");
var defaults_1 = tslib_1.__importDefault(require("../text-field/defaults"));
var defaults_2 = tslib_1.__importDefault(require("../assistive-text/defaults"));
var radio_button_1 = require("../radio-button");
var text_area_1 = require("../text-area");
var character_count_1 = require("../character-count");
var useFormFieldContext = function () { return (0, react_1.useContext)(context_1.FormInputContext); };
var setState = function (state, isRequired, hasContent) {
    var isOptionalAndEmpty = !isRequired && !hasContent && state === 'valid';
    if (isOptionalAndEmpty)
        return undefined;
    return state;
};
var ThemelessFormInput = function (_a) {
    var name = _a.name, rules = _a.rules, stateProp = _a.state, size = _a.size, children = _a.children, id = _a.id;
    var defaultSize = 'medium';
    var autoGeneratedId = (0, hooks_1.useReactKeys)(1)[0];
    var currentID = id || autoGeneratedId;
    var _b = (0, react_1.useState)(), assistiveTextId = _b[0], setAssistiveTextId = _b[1];
    var theme = (0, theme_1.useTheme)();
    var validationIconSize = (0, get_token_1.getToken)({ theme: theme, overrides: {} }, "textField.".concat(size || defaultSize, ".endEnhancer"), 'endEnhancer', 'iconSize');
    var passedInputFieldContext = useFormFieldContext();
    return (react_1.default.createElement(form_entry_1.FormEntry, { name: name, rules: rules }, function (_a) {
        var ref = _a.ref, stateContext = _a.state, onChange = _a.onChange, onBlur = _a.onBlur, error = _a.error, refObject = _a.refObject, hasContent = _a.hasContent;
        var isRequired = rules && rules.required !== undefined;
        var state = stateProp || setState(stateContext, isRequired, hasContent);
        var labelId = "".concat(currentID, "-label");
        var statusIcon = (0, utils_1.getStatusIcon)({ state: state, iconSize: validationIconSize });
        var inputFieldContext = {
            name: name,
            size: size || passedInputFieldContext.size || defaultSize,
            onChange: onChange,
            onBlur: onBlur,
            state: state,
            error: error,
            ref: ref,
            id: currentID,
            assistiveTextId: assistiveTextId,
            setAssistiveTextId: setAssistiveTextId,
            labelId: labelId,
            statusIcon: statusIcon,
            isRequired: isRequired,
            refObject: refObject,
            rules: rules,
        };
        return (react_1.default.createElement(context_1.FormInputContext.Provider, { value: inputFieldContext }, children));
    }));
};
exports.FormInput = (0, with_own_theme_1.withOwnTheme)(ThemelessFormInput)({
    defaults: tslib_1.__assign(tslib_1.__assign({}, defaults_1.default), defaults_2.default),
});
exports.FormInputTextField = react_1.default.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, endEnhancer = _a.endEnhancer, props = tslib_1.__rest(_a, ["children", "onChange", "onBlur", "endEnhancer"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, statusIcon = _b.statusIcon, isRequired = _b.isRequired;
    function getEndEnhancer() {
        if (!statusIcon) {
            return endEnhancer;
        }
        if (endEnhancer) {
            return (react_1.default.createElement(react_1.default.Fragment, null,
                statusIcon,
                " ",
                react_1.default.createElement(block_1.Block, { spaceInline: "space020" }),
                " ",
                endEnhancer,
                ' '));
        }
        return statusIcon;
    }
    return (react_1.default.createElement(text_field_1.TextField, tslib_1.__assign({ "aria-required": isRequired || undefined, "aria-invalid": state === 'invalid' ? 'true' : 'false', name: name, state: state, size: size, onChange: (0, compose_event_handlers_1.composeEventHandlers)([onChange, onChangeContext]), onBlur: (0, compose_event_handlers_1.composeEventHandlers)([onBlur, onBlurContext]), ref: (0, compose_react_refs_1.default)(ref, inputRef), endEnhancer: getEndEnhancer(), id: id, "aria-describedby": assistiveTextId }, props)));
});
var FormInputLabel = function (_a) {
    var children = _a.children, props = tslib_1.__rest(_a, ["children"]);
    var _b = useFormFieldContext(), size = _b.size, state = _b.state, id = _b.id, labelId = _b.labelId;
    return (react_1.default.createElement(label_1.Label, tslib_1.__assign({ id: labelId, size: size, state: state, htmlFor: id }, props), children));
};
exports.FormInputLabel = FormInputLabel;
exports.FormInputSelect = react_1.default.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = tslib_1.__rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, labelId = _b.labelId, statusIcon = _b.statusIcon, isRequired = _b.isRequired;
    return (react_1.default.createElement(select_1.Select, tslib_1.__assign({ name: name, state: state, size: size, "aria-labelledby": "".concat(labelId, " ").concat(id), validationIcon: statusIcon, onChange: (0, compose_event_handlers_1.composeEventHandlers)([onChange, onChangeContext]), onBlur: (0, compose_event_handlers_1.composeEventHandlers)([onBlur, onBlurContext]), ref: (0, compose_react_refs_1.default)(ref, inputRef), id: id, labelId: labelId, "aria-describedby": assistiveTextId, required: isRequired || undefined }, props), children));
});
var FormInputAssistiveText = function (_a) {
    var children = _a.children, _b = _a.validationIcon, validationIcon = _b === void 0 ? false : _b, overrides = _a.overrides, props = tslib_1.__rest(_a, ["children", "validationIcon", "overrides"]);
    var _c = useFormFieldContext(), size = _c.size, state = _c.state, error = _c.error, assistiveTextId = _c.assistiveTextId, setAssistiveTextId = _c.setAssistiveTextId, id = _c.id;
    (0, react_1.useEffect)(function () {
        if (setAssistiveTextId) {
            setAssistiveTextId(state === 'invalid' ? "".concat(id, "-error-text") : "".concat(id, "-assistive-text"));
        }
    }, [state, id, setAssistiveTextId]);
    var theme = (0, theme_1.useTheme)();
    var validationIconSize = (0, get_token_1.getToken)({ theme: theme, overrides: {} }, "assistiveText.".concat(size, ".startEnhancer"), 'startEnhancer', 'iconSize');
    var statusIcon = (0, utils_1.getStatusIcon)({ state: state, iconSize: validationIconSize });
    return (react_1.default.createElement(assistive_text_1.AssistiveText, tslib_1.__assign({ size: size, state: state, id: assistiveTextId, startEnhancer: validationIcon ? statusIcon : undefined, overrides: overrides }, props), error || children));
};
exports.FormInputAssistiveText = FormInputAssistiveText;
exports.FormInputCheckbox = react_1.default.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = tslib_1.__rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (react_1.default.createElement(checkbox_1.Checkbox, tslib_1.__assign({ name: name, state: state, size: size, onChange: (0, compose_event_handlers_1.composeEventHandlers)([onChange, onChangeContext]), onBlur: (0, compose_event_handlers_1.composeEventHandlers)([onBlur, onBlurContext]), ref: (0, compose_react_refs_1.default)(ref, inputRef), id: id, "aria-describedby": assistiveTextId, "aria-required": isRequired || undefined }, props)));
});
exports.FormInputRadioButton = react_1.default.forwardRef(function (_a, inputRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = tslib_1.__rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (react_1.default.createElement(radio_button_1.RadioButton, tslib_1.__assign({ name: name, state: state, size: size, onChange: (0, compose_event_handlers_1.composeEventHandlers)([onChange, onChangeContext]), onBlur: (0, compose_event_handlers_1.composeEventHandlers)([onBlur, onBlurContext]), ref: (0, compose_react_refs_1.default)(ref, inputRef), id: id, "aria-describedby": assistiveTextId, "aria-required": isRequired || undefined }, props)));
});
exports.FormInputTextArea = react_1.default.forwardRef(function (_a, elementRef) {
    var children = _a.children, onChange = _a.onChange, onBlur = _a.onBlur, props = tslib_1.__rest(_a, ["children", "onChange", "onBlur"]);
    var _b = useFormFieldContext(), size = _b.size, name = _b.name, state = _b.state, onChangeContext = _b.onChange, onBlurContext = _b.onBlur, ref = _b.ref, id = _b.id, assistiveTextId = _b.assistiveTextId, isRequired = _b.isRequired;
    return (react_1.default.createElement(text_area_1.TextArea, tslib_1.__assign({ "aria-required": isRequired || undefined, "aria-invalid": state === 'invalid' ? 'true' : 'false', name: name, state: state, size: size, onChange: (0, compose_event_handlers_1.composeEventHandlers)([onChange, onChangeContext]), onBlur: (0, compose_event_handlers_1.composeEventHandlers)([onBlur, onBlurContext]), ref: (0, compose_react_refs_1.default)(elementRef, ref), id: id, "aria-describedby": assistiveTextId }, props)));
});
function isValidationValueMessage(valueOrObj) {
    return valueOrObj.value !== undefined;
}
function asNumber(value) {
    if (typeof value === 'string') {
        return parseInt(value, 10);
    }
    return value;
}
var getValueFromRule = function (value) {
    if (!!value && isValidationValueMessage(value)) {
        return asNumber(value.value);
    }
    if (value) {
        return asNumber(value);
    }
    return undefined;
};
var FormInputCharacterCount = function (props) {
    var _a = useFormFieldContext(), refObject = _a.refObject, state = _a.state, size = _a.size, rules = _a.rules;
    var _b = (rules || {}), minLength = _b.minLength, maxLength = _b.maxLength;
    return (react_1.default.createElement(character_count_1.CharacterCount, tslib_1.__assign({ state: state, size: size, inputRef: refObject, minLength: getValueFromRule(minLength), maxLength: getValueFromRule(maxLength) }, props)));
};
exports.FormInputCharacterCount = FormInputCharacterCount;
//# sourceMappingURL=form-input.js.map