/// <reference types="trusted-types" />
import React from 'react';
import { FormProps, FormInputState } from './types';
export declare const getStatusIcon: ({ state, validIcon, invalidIcon, iconSize, }: {
    state?: FormInputState;
    validIcon?: React.ReactNode;
    invalidIcon?: React.ReactNode;
    iconSize: string;
}) => React.ReactNode;
export declare const excludeReactHookFormProps: (props: FormProps) => {
    children: React.ReactNode;
    onSubmit: import("react-hook-form").SubmitHandler<Record<string, any>>;
    onSubmitInvalid?: import("react-hook-form").SubmitErrorHandler<Record<string, string>> | undefined;
    manifest?: string | undefined;
    defaultChecked?: boolean | undefined;
    defaultValue?: string | number | readonly string[] | undefined;
    suppressContentEditableWarning?: boolean | undefined;
    suppressHydrationWarning?: boolean | undefined;
    accessKey?: string | undefined;
    autoCapitalize?: (string & {}) | "none" | "off" | "on" | "sentences" | "words" | "characters" | undefined;
    autoFocus?: boolean | undefined;
    className?: string | undefined;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only" | undefined;
    contextMenu?: string | undefined;
    dir?: string | undefined;
    draggable?: (boolean | "false" | "true") | undefined;
    enterKeyHint?: "search" | "enter" | "next" | "done" | "go" | "previous" | "send" | undefined;
    hidden?: boolean | undefined;
    id?: string | undefined;
    lang?: string | undefined;
    nonce?: string | undefined;
    slot?: string | undefined;
    spellCheck?: (boolean | "false" | "true") | undefined;
    style?: React.CSSProperties | undefined;
    tabIndex?: number | undefined;
    title?: string | undefined;
    translate?: "no" | "yes" | undefined;
    radioGroup?: string | undefined;
    role?: React.AriaRole | undefined;
    about?: string | undefined;
    content?: string | undefined;
    datatype?: string | undefined;
    inlist?: any;
    prefix?: string | undefined;
    property?: string | undefined;
    rel?: string | undefined;
    resource?: string | undefined;
    rev?: string | undefined;
    typeof?: string | undefined;
    vocab?: string | undefined;
    autoCorrect?: string | undefined;
    autoSave?: string | undefined;
    color?: string | undefined;
    itemProp?: string | undefined;
    itemScope?: boolean | undefined;
    itemType?: string | undefined;
    itemID?: string | undefined;
    itemRef?: string | undefined;
    results?: number | undefined;
    security?: string | undefined;
    unselectable?: "off" | "on" | undefined;
    popover?: "" | "auto" | "manual" | undefined;
    popoverTargetAction?: "hide" | "show" | "toggle" | undefined;
    popoverTarget?: string | undefined;
    inert?: boolean | undefined;
    inputMode?: "none" | "search" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | undefined;
    is?: string | undefined;
    exportparts?: string | undefined;
    part?: string | undefined;
    "aria-activedescendant"?: string | undefined;
    "aria-atomic"?: (boolean | "false" | "true") | undefined;
    "aria-autocomplete"?: "none" | "both" | "inline" | "list" | undefined;
    "aria-braillelabel"?: string | undefined;
    "aria-brailleroledescription"?: string | undefined;
    "aria-busy"?: (boolean | "false" | "true") | undefined;
    "aria-checked"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-colcount"?: number | undefined;
    "aria-colindex"?: number | undefined;
    "aria-colindextext"?: string | undefined;
    "aria-colspan"?: number | undefined;
    "aria-controls"?: string | undefined;
    "aria-current"?: boolean | "time" | "page" | "false" | "true" | "step" | "location" | "date" | undefined;
    "aria-describedby"?: string | undefined;
    "aria-description"?: string | undefined;
    "aria-details"?: string | undefined;
    "aria-disabled"?: (boolean | "false" | "true") | undefined;
    "aria-dropeffect"?: "none" | "link" | "copy" | "move" | "execute" | "popup" | undefined;
    "aria-errormessage"?: string | undefined;
    "aria-expanded"?: (boolean | "false" | "true") | undefined;
    "aria-flowto"?: string | undefined;
    "aria-grabbed"?: (boolean | "false" | "true") | undefined;
    "aria-haspopup"?: boolean | "dialog" | "menu" | "grid" | "listbox" | "false" | "true" | "tree" | undefined;
    "aria-hidden"?: (boolean | "false" | "true") | undefined;
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
    "aria-keyshortcuts"?: string | undefined;
    "aria-label"?: string | undefined;
    "aria-labelledby"?: string | undefined;
    "aria-level"?: number | undefined;
    "aria-live"?: "off" | "assertive" | "polite" | undefined;
    "aria-modal"?: (boolean | "false" | "true") | undefined;
    "aria-multiline"?: (boolean | "false" | "true") | undefined;
    "aria-multiselectable"?: (boolean | "false" | "true") | undefined;
    "aria-orientation"?: "horizontal" | "vertical" | undefined;
    "aria-owns"?: string | undefined;
    "aria-placeholder"?: string | undefined;
    "aria-posinset"?: number | undefined;
    "aria-pressed"?: boolean | "mixed" | "false" | "true" | undefined;
    "aria-readonly"?: (boolean | "false" | "true") | undefined;
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals" | undefined;
    "aria-required"?: (boolean | "false" | "true") | undefined;
    "aria-roledescription"?: string | undefined;
    "aria-rowcount"?: number | undefined;
    "aria-rowindex"?: number | undefined;
    "aria-rowindextext"?: string | undefined;
    "aria-rowspan"?: number | undefined;
    "aria-selected"?: (boolean | "false" | "true") | undefined;
    "aria-setsize"?: number | undefined;
    "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
    "aria-valuemax"?: number | undefined;
    "aria-valuemin"?: number | undefined;
    "aria-valuenow"?: number | undefined;
    "aria-valuetext"?: string | undefined;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    } | undefined;
    onCopy?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onCopyCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onCut?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onCutCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onPaste?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onPasteCapture?: React.ClipboardEventHandler<HTMLFormElement> | undefined;
    onCompositionEnd?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onCompositionEndCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onCompositionStart?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onCompositionStartCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onCompositionUpdate?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLFormElement> | undefined;
    onFocus?: React.FocusEventHandler<HTMLFormElement> | undefined;
    onFocusCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
    onBlur?: React.FocusEventHandler<HTMLFormElement> | undefined;
    onBlurCapture?: React.FocusEventHandler<HTMLFormElement> | undefined;
    onChange?: React.FormEventHandler<HTMLFormElement> | undefined;
    onChangeCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onBeforeInput?: React.InputEventHandler<HTMLFormElement> | undefined;
    onBeforeInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onInput?: React.FormEventHandler<HTMLFormElement> | undefined;
    onInputCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onReset?: React.FormEventHandler<HTMLFormElement> | undefined;
    onResetCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onSubmitCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onInvalid?: React.FormEventHandler<HTMLFormElement> | undefined;
    onInvalidCapture?: React.FormEventHandler<HTMLFormElement> | undefined;
    onLoad?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onError?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onErrorCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onKeyDown?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onKeyDownCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onKeyPress?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onKeyPressCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onKeyUp?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onKeyUpCapture?: React.KeyboardEventHandler<HTMLFormElement> | undefined;
    onAbort?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onAbortCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onCanPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onCanPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onCanPlayThrough?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onCanPlayThroughCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onDurationChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onDurationChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEmptied?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEmptiedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEncrypted?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEncryptedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEnded?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onEndedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadedData?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadedDataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadedMetadata?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadedMetadataCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadStart?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onLoadStartCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPause?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPauseCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPlay?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPlayCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPlaying?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onPlayingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onProgress?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onProgressCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onRateChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onRateChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSeeked?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSeekedCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSeeking?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSeekingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onStalled?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onStalledCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSuspend?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSuspendCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onTimeUpdate?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onTimeUpdateCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onVolumeChange?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onVolumeChangeCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onWaiting?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onWaitingCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onAuxClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onAuxClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onContextMenu?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onContextMenuCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onDoubleClick?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onDoubleClickCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onDrag?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragEnd?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragEndCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragEnter?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragEnterCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragExit?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragExitCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragLeave?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragLeaveCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragOver?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragOverCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragStart?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDragStartCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDrop?: React.DragEventHandler<HTMLFormElement> | undefined;
    onDropCapture?: React.DragEventHandler<HTMLFormElement> | undefined;
    onMouseDown?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseDownCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseEnter?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseLeave?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseMove?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseMoveCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseOut?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseOutCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseOver?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseOverCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseUp?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onMouseUpCapture?: React.MouseEventHandler<HTMLFormElement> | undefined;
    onSelect?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onSelectCapture?: React.ReactEventHandler<HTMLFormElement> | undefined;
    onTouchCancel?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchCancelCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchEnd?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchEndCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchMove?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchMoveCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchStart?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onTouchStartCapture?: React.TouchEventHandler<HTMLFormElement> | undefined;
    onPointerDown?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerDownCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerMove?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerMoveCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerUp?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerUpCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerCancel?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerCancelCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerEnter?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerLeave?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerOver?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerOverCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerOut?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onPointerOutCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onGotPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onLostPointerCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLFormElement> | undefined;
    onScroll?: React.UIEventHandler<HTMLFormElement> | undefined;
    onScrollCapture?: React.UIEventHandler<HTMLFormElement> | undefined;
    onScrollEnd?: React.UIEventHandler<HTMLFormElement> | undefined;
    onScrollEndCapture?: React.UIEventHandler<HTMLFormElement> | undefined;
    onWheel?: React.WheelEventHandler<HTMLFormElement> | undefined;
    onWheelCapture?: React.WheelEventHandler<HTMLFormElement> | undefined;
    onAnimationStart?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onAnimationStartCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onAnimationEnd?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onAnimationEndCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onAnimationIteration?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onAnimationIterationCapture?: React.AnimationEventHandler<HTMLFormElement> | undefined;
    onToggle?: React.ToggleEventHandler<HTMLFormElement> | undefined;
    onBeforeToggle?: React.ToggleEventHandler<HTMLFormElement> | undefined;
    onTransitionCancel?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionCancelCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionEnd?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionEndCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionRun?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionRunCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionStart?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    onTransitionStartCapture?: React.TransitionEventHandler<HTMLFormElement> | undefined;
    marginInlineStart?: import("..").MQ<string> | undefined;
    marginInlineEnd?: import("..").MQ<string> | undefined;
    marginInline?: import("..").MQ<string> | undefined;
    marginBlockStart?: import("..").MQ<string> | undefined;
    marginBlockEnd?: import("..").MQ<string> | undefined;
    marginBlock?: import("..").MQ<string> | undefined;
    paddingInlineStart?: import("..").MQ<string> | undefined;
    paddingInlineEnd?: import("..").MQ<string> | undefined;
    paddingInline?: import("..").MQ<string> | undefined;
    paddingBlockStart?: import("..").MQ<string> | undefined;
    paddingBlockEnd?: import("..").MQ<string> | undefined;
    paddingBlock?: import("..").MQ<string> | undefined;
};
//# sourceMappingURL=utils.d.ts.map