Name:
  ncu-newskit
DocSiteName:
  ncu-newskit-doc-site
StorybookName:
  ncu-newskit-storybook
Environment:
  prod
Namespace:
  newskit-prod
NewsUKcidr:
  0.0.0.0/0
FQDN:
  newskit.prod.ceng.newsuk.tech
FQDNStorybook:
  newskit-storybook.prod.ceng.newsuk.tech
SSLCertARN:
  # this cert is for *.prod.ceng.newsuk.tech
  arn:aws:acm:eu-west-1:474887192380:certificate/ec49c52e-1347-4150-a577-276b397f2c53
resources:
  limits:
    cpu: "0.5"
    memory: 1Gi
  requests:
    cpu: "0.5"
    memory: 1Gi
